#+TITLE: Doom Emacs ABCs
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
#+OPTIONS: num:nil

* Overview
:PROPERTIES:
:CUSTOM_ID: OVERVIEW
:END:
** SPC RET 
#+NAME: SPCRET
| Key       | Command       |
|-----------+---------------|
| ~SPC RET~ | [[#7936b19a-9919-4a32-807c-ecf9dd289a82][bookmark-jump]] |
** SPC SPC 
#+NAME: SPCSPC
| Key       | Command              |
|-----------+----------------------|
| ~SPC SPC~ | [[#4713167e-f20a-4651-890d-3f92c3a79651][projectile-find-file]] |
** SPC ' 
#+NAME: SPC'
| Key     | Command    |
|---------+------------|
| ~SPC '~ | [[#c8a625ed-3383-4f8a-bd85-35fb950a75e1][ivy-resume]] |
** SPC , 
#+NAME: SPC,
| Key     | Command                |
|---------+------------------------|
| ~SPC ,~ | [[#d16eacde-6905-4cd9-835d-ba3953329aee][persp-switch-to-buffer]] |
** SPC . 
#+NAME: SPC.
| Key     | Command   |
|---------+-----------|
| ~SPC .~ | [[#39ec3fd1-540f-4560-8e87-be4b99176816][find-file]] |
** SPC : 
#+NAME: SPC:
| Key     | Command                  |
|---------+--------------------------|
| ~SPC :~ | [[#ad1749ea-3bed-4e19-98e3-970347cf0283][execute-extended-command]] |
** SPC ; 
#+NAME: SPC;
| Key     | Command         |
|---------+-----------------|
| ~SPC ;~ | [[#c224b829-388d-45df-b6bd-19f844e45bef][eval-expression]] |
** SPC < 
#+NAME: SPC<
| Key     | Command          |
|---------+------------------|
| ~SPC <~ | [[#71111500-75ee-4a40-aa12-0a2926cb1271][switch-to-buffer]] |
** SPC X 
#+NAME: SPCX
| Key     | Command     |
|---------+-------------|
| ~SPC X~ | [[#006737f1-ad10-4cf4-bccf-c1e66bd3cdad][org-capture]] |
** SPC u 
#+NAME: SPCu
| Key     | Command            |
|---------+--------------------|
| ~SPC u~ | [[#e1cccaea-a301-44c5-8ca4-6bff866b22ea][universal-argument]] |
** SPC x 
#+NAME: SPCx
| Key     | Command                  |
|---------+--------------------------|
| ~SPC x~ | [[#8c7db950-b793-45e0-8101-7ee41ff11c92][doom/open-scratch-buffer]] |
** SPC ~ 
#+NAME: SPC~
| Key     | Command       |
|---------+---------------|
| ~SPC ~~ | [[#b6d4765b-9eb8-41f6-a3a9-2db456b42e37][+popup/toggle]] |
** SPC DEL 
#+NAME: SPCDEL
| Key       | Command                 |
|-----------+-------------------------|
| ~SPC DEL~ | [[#f110201c-49d0-4041-806b-84072bee6352][+nav-flash/blink-cursor]] |
** SPC t 
#+NAME: SPCt
| Key       | Command                  |
|-----------+--------------------------|
| ~SPC t b~ | [[#7877ad19-4225-4137-b37f-b3fb6d445cd0][doom-big-font-mode]]       |
| ~SPC t f~ | [[#cf79b310-5340-4cc6-acf3-183d0d6f71f3][flycheck-mode]]            |
| ~SPC t g~ | [[#d2f0ecdf-b69d-4918-bec1-993edb3e302b][evil-goggles-mode]]        |
| ~SPC t l~ | [[#90e112e3-64bc-4247-a74b-b4b1da799018][doom/toggle-line-numbers]] |
| ~SPC t p~ | [[#3ead99f5-ba3d-47bf-a795-02272a000b6a][+org-present/start]]       |
| ~SPC t s~ | [[#090e14b7-ab60-42dd-8511-1c7656e87166][flyspell-mode]]            |
| ~SPC t F~ | [[#0f780fa8-2f15-4077-9934-57fc3e8f0898][toggle-frame-fullscreen]]  |
** SPC s 
#+NAME: SPCs
| Key       | Command                |
|-----------+------------------------|
| ~SPC s S~ | [[#889b267b-7414-4d9c-b4cb-387d4e9a6999][+snippets/browse]]       |
| ~SPC s c~ | [[#9d955af1-310d-4784-a1bc-d327e7341781][aya-create]]             |
| ~SPC s e~ | [[#b9124888-c7c2-4e01-8b0f-a1bc7b0aced9][aya-expand]]             |
| ~SPC s i~ | [[#d805ed3b-78c5-456a-bae0-4321f8a003cc][yas-insert-snippet]]     |
| ~SPC s n~ | [[#4d74ec66-e879-41f4-9163-ea1359c56bba][yas-new-snippet]]        |
| ~SPC s r~ | [[#c3f81cf7-900e-495d-a9a1-436b993c599b][yas-reload-all]]         |
| ~SPC s s~ | [[#9a2dd41f-1e7a-4ec9-a341-e3ddd3404383][+snippets/find-file]]    |
| ~SPC s /~ | [[#113b6660-4c14-446d-ba44-75e4b9afdfc8][yas-visit-snippet-file]] |
** SPC q 
#+NAME: SPCq
| Key       | Command                  |
|-----------+--------------------------|
| ~SPC q Q~ | [[#9453f505-66e6-4bb3-bda0-728697a281bd][evil-save-and-quit]]       |
| ~SPC q R~ | [[#c81e453e-0bfc-4a07-a297-bde25a2b1fbb][doom/restart]]             |
| ~SPC q S~ | [[#43795568-2f93-4159-813f-a07fbff4cd07][doom/save-session]]        |
| ~SPC q l~ | [[#cfde721c-2f66-456b-904a-bda350c71f02][doom/quickload-session]]   |
| ~SPC q q~ | [[#189958eb-b7bf-45b2-a78a-0821d48e1f52][evil-quit-all]]            |
| ~SPC q r~ | [[#9c59ab4b-cda8-4024-9b55-6bdef57e0957][doom/restart-and-restore]] |
| ~SPC q s~ | [[#2bff6a9c-08a4-4a62-8ac3-a04cd9f6a04f][doom/quicksave-session]]   |
| ~SPC q L~ | [[#1a2539cf-159f-4359-9cf6-07201d908303][doom/load-session]]        |
** SPC p 
#+NAME: SPCp
| Key       | Command                              |
|-----------+--------------------------------------|
| ~SPC p .~ | [[#8adcff30-082b-43ca-9027-c383bb9a961e][+default/browse-project]]              |
| ~SPC p /~ | [[#51bd426b-db4d-4b12-a430-e80f4dcbfa85][projectile-find-file]]                 |
| ~SPC p c~ | [[#47046a75-53c9-4c72-8cf2-3e2db47d816f][projectile-compile-project]]           |
| ~SPC p o~ | [[#5447c09f-e5eb-4899-a744-d2cebcdf2f57][projectile-find-other-file]]           |
| ~SPC p p~ | [[#72b618d1-aea8-4c99-b689-a00c8cc51ab1][projectile-switch-project]]            |
| ~SPC p r~ | [[#4b91f61d-98cd-40b3-8bf2-39a9354dddb6][projectile-recentf]]                   |
| ~SPC p t~ | [[#5f2bb02e-35aa-42f5-893f-71e5bfb5091b][+default/project-tasks]]               |
| ~SPC p x~ | [[#850d3af7-ce60-4799-9fa6-bf3997eb870c][projectile-invalidate-cache]]          |
| ~SPC p !~ | [[#edc660f7-f5c1-4d10-b263-58b815bee729][projectile-run-shell-command-in-root]] |
** SPC o 
#+NAME: SPCo
| Key       | Command                      |
|-----------+------------------------------|
| ~SPC o A~ | [[#097c5064-d98a-4402-9e02-4328014d4f9e][org-agenda]]                   |
| ~SPC o P~ | [[#f2ca4317-57a8-4481-aaf6-53be7cf88e53][+treemacs/find-file]]          |
| ~SPC o R~ | [[#c3ed250b-7275-449b-b46a-2f9fe9736f31][+eval/open-repl-same-window]]  |
| ~SPC o b~ | [[#c42d56df-1cd5-4aaa-bc93-4393b9ed1f94][browse-url-of-file]]           |
| ~SPC o i~ | [[#d1b28c1a-f878-4271-b6eb-3d16abf595fb][imenu-list-smart-toggle]]      |
| ~SPC o p~ | [[#c1b8aaee-e425-4f5c-9a73-3321ecc0eff2][+treemacs/toggle]]             |
| ~SPC o r~ | [[#60d23955-d838-4d50-94d7-77e1a60448f6][+eval/open-repl-other-window]] |
| ~SPC o -~ | [[#cf15003c-9c45-4044-9a5f-628835450c00][dired-jump]]                   |
** SPC n 
#+NAME: SPCn
| Key       | Command                  |
|-----------+--------------------------|
| ~SPC n l~ | [[#318398e5-b23b-440a-8e32-f84b010f3faf][org-store-link]]           |
| ~SPC n n~ | [[#4377760d-a48e-437a-ab3f-a60e293b2926][+default/find-in-notes]]   |
| ~SPC n s~ | [[#b4023007-9482-426c-8a2e-f2261e36d39a][doom/open-scratch-buffer]] |
| ~SPC n x~ | [[#9e2f7a7e-0456-4b0e-b853-e19620ab8b25][org-capture]]              |
| ~SPC n N~ | [[#5b2fe451-598f-4739-8f6f-3027f9ddbbad][+default/browse-notes]]    |
** SPC i 
#+NAME: SPCi
| Key       | Command            |
|-----------+--------------------|
| ~SPC i y~ | [[#80846462-575f-4adc-b4c6-f563337a9c47][+default/yank-pop]]  |
| ~SPC i s~ | [[#167a000a-6b35-4011-8b90-993a3fb10742][yas-insert-snippet]] |
** SPC g 
#+NAME: SPCg
| Key       | Command                  |
|-----------+--------------------------|
| ~SPC g /~ | [[#6f45bf0d-db98-495e-aaf3-26a44bce0597][magit-dispatch]]           |
| ~SPC g B~ | [[#377b1f0b-1c85-4e1d-ba8a-c9b07f9216dd][magit-blame-addition]]     |
| ~SPC g C~ | [[#87afe0af-944b-44b4-849d-57648d9f14d8][+magit/clone]]             |
| ~SPC g F~ | [[#06a048fd-2d5b-4871-8bb7-8e428684d131][magit-fetch]]              |
| ~SPC g L~ | [[#80de298e-bec2-4877-b78a-aab7b7fa1698][magit-log]]                |
| ~SPC g R~ | [[#20950724-b6d1-4143-9c9d-d7eb9a535b64][vc-revert]]                |
| ~SPC g S~ | [[#cab158d6-a07a-447f-a7f3-7c3b903bf94d][magit-stage-file]]         |
| ~SPC g U~ | [[#492ddbd7-269c-4dbf-9209-0875e5dc9aa2][magit-unstage-file]]       |
| ~SPC g [~ | [[#2e9e00d3-ffb1-43b6-b820-b68de20565ef][git-gutter:previous-hunk]] |
| ~SPC g ]~ | [[#078333bc-daed-46e2-bec8-546f48f572ee][git-gutter:next-hunk]]     |
| ~SPC g g~ | [[#be633158-9952-4c3e-9c11-3c0915a99e99][magit-status]]             |
| ~SPC g r~ | [[#0e371fe0-8c93-4596-aae2-023e21069724][git-gutter:revert-hunk]]   |
| ~SPC g s~ | [[#a03374e4-b9d7-4aa7-a006-6fd9a77ffc70][git-gutter:stage-hunk]]    |
| ~SPC g t~ | [[#ebf87a91-7c8f-4b7c-a26e-eb5c86eb95dc][git-timemachine-toggle]]   |
| ~SPC g x~ | [[#0f58bd0b-d0b4-49eb-b107-34902a0f7932][magit-file-delete]]        |
| ~SPC g '~ | [[#6447d2ac-f678-4d5e-80ac-ef5c1c420634][forge-dispatch]]           |
** SPC f 
#+NAME: SPCf
| Key       | Command                          |
|-----------+----------------------------------|
| ~SPC f /~ | [[#f23a7abe-065b-49c9-a5a7-5cd4e8f65cc6][projectile-find-file]]             |
| ~SPC f >~ | [[#6a963989-407e-47be-991c-b6afeea51272][doom/browse-in-other-project]]     |
| ~SPC f ?~ | [[#bdba04d7-0cbb-42ec-a096-6550940351d6][doom/find-file-in-other-project]]  |
| ~SPC f E~ | [[#4fa53e94-1db1-4731-9b4e-a89d794c450e][+default/browse-emacsd]]           |
| ~SPC f P~ | [[#c4451e27-8e04-4d00-84a1-db425b616e4f][doom/open-private-config]]         |
| ~SPC f R~ | [[#3626d691-a3ee-445a-a50f-d93adfaf6f01][projectile-recentf]]               |
| ~SPC f S~ | [[#cfe21cbd-4efc-4226-8be4-7277a462b5cb][doom/sudo-find-file]]              |
| ~SPC f X~ | [[#04a5ae29-a371-48fc-a7bb-184256008ef6][doom/delete-this-file]]            |
| ~SPC f a~ | [[#6419c48c-ad36-4493-8701-8ec2a35c7162][projectile-find-other-file]]       |
| ~SPC f d~ | [[#75cdd776-f4e5-4a10-9d6f-5252b97ce1ab][dired]]                            |
| ~SPC f e~ | [[#7c44ae79-82ff-425e-9646-3b6e8f3ccbf7][+default/find-in-emacsd]]          |
| ~SPC f f~ | [[#5d5b3a2c-c39c-49cb-bb48-cad996dabd08][find-file]]                        |
| ~SPC f p~ | [[#38bb4388-3d65-4116-95fd-c63ffc58eea9][doom/find-file-in-private-config]] |
| ~SPC f r~ | [[#c76562db-cd7f-475e-9e01-0eed9d61cb46][recentf-open-files]]               |
| ~SPC f s~ | [[#6fa9b87e-7273-4e35-a6a9-0de4d9fd56c3][save-buffer]]                      |
| ~SPC f y~ | [[#441e0cdb-7ce9-471c-8411-447af37b90ff][+default/yank-buffer-filename]]    |
| ~SPC f .~ | [[#0bd9a0f1-550e-4eac-98f9-179c5e67d024][counsel-file-jump]]                |
** SPC c 
#+NAME: SPCc
| Key       | Command                       |
|-----------+-------------------------------|
| ~SPC c E~ | [[#0b1547c3-b51b-49a7-b0e1-d5abd7b131d7][+eval:replace-region]]          |
| ~SPC c W~ | [[#0e356afa-02ab-442c-8ac4-f77a3ad03f3d][doom/delete-trailing-newlines]] |
| ~SPC c c~ | [[#277e3f79-00c7-4255-ac55-c3b770bab810][projectile-compile-project]]    |
| ~SPC c d~ | [[#d4268002-10f5-40c7-ab2c-58cbae78c974][+lookup/definition]]            |
| ~SPC c e~ | [[#6f7dd680-12ba-44b4-87c9-c7e8054f5850][+eval/buffer-or-region]]        |
| ~SPC c r~ | [[#07a72872-94ed-4ad6-9ddf-572e8177e0bd][+eval/open-repl-other-window]]  |
| ~SPC c w~ | [[#2ff4d4df-7cc0-430c-928c-675e646edc7d][delete-trailing-whitespace]]    |
| ~SPC c x~ | [[#af582e8f-e43a-4a37-809b-8510d74afb05][flycheck-list-errors]]          |
| ~SPC c D~ | [[#329cef26-e505-43a0-9d31-0a9362418419][+lookup/references]]            |
** SPC b 
#+NAME: SPCb
| Key       | Command                      |
|-----------+------------------------------|
| ~SPC b B~ | [[#d68f0498-9d90-4b97-87e8-1ad5baadc464][switch-to-buffer]]             |
| ~SPC b N~ | [[#68fad855-9f08-4968-b4e8-8ade54aae707][evil-buffer-new]]              |
| ~SPC b S~ | [[#f0e6c89e-63f3-41a5-9133-384256d5db13][doom/sudo-this-file]]          |
| ~SPC b [~ | [[#023ee488-f3ba-433d-868a-05d27aec24cc][previous-buffer]]              |
| ~SPC b ]~ | [[#f5b38e30-260e-43f7-be4c-d4c13a8d0ede][next-buffer]]                  |
| ~SPC b b~ | [[#319f4d01-a04e-4d89-a13c-361e8b65468a][persp-switch-to-buffer]]       |
| ~SPC b k~ | [[#41f8111a-a787-4f38-af71-0e9f408fd147][kill-this-buffer]]             |
| ~SPC b n~ | [[#007139e3-8613-4a6e-9f49-6049f783ffc0][next-buffer]]                  |
| ~SPC b o~ | [[#4a1355ad-d96a-40a3-a3e5-2c5769cafe01][doom/kill-other-buffers]]      |
| ~SPC b p~ | [[#24f4e616-c3c6-4266-88b8-404c61dbc4aa][previous-buffer]]              |
| ~SPC b s~ | [[#2a015be2-eb68-4fd4-ba8a-d4d8df158744][save-buffer]]                  |
| ~SPC b x~ | [[#5b5d44ab-77db-4c39-b0a1-6006acca30a9][doom/open-scratch-buffer]]     |
| ~SPC b z~ | [[#911f8f07-dede-4c86-923c-208c6c6e18d5][bury-buffer]]                  |
| ~SPC b -~ | [[#28a6d99e-0812-4332-8745-af9dbd1dc37f][doom/clone-and-narrow-buffer]] |
** SPC TAB 
#+NAME: SPCTAB
| Key           | Command                         |
|---------------+---------------------------------|
| ~SPC TAB .~   | [[#5019af10-619a-4507-a3af-0702eb4c0600][+workspace/switch-to]]            |
| ~SPC TAB 0~   | [[#1d03d4d8-bd19-4736-9626-cd3579aa4a68][+workspace/switch-to-last]]       |
| ~SPC TAB R~   | [[#14096506-e779-4166-8702-9f2e79f19a3e][+workspace/restore-last-session]] |
| ~SPC TAB [~   | [[#ad502bba-1099-4c4a-afec-7087d6f04137][+workspace/switch-left]]          |
| ~SPC TAB ]~   | [[#beb80fa5-ca53-4ee3-9eb1-a1588c5430f8][+workspace/switch-right]]         |
| ~SPC TAB d~   | [[#fcd7879a-0a00-4448-a508-8f0ed3249a5e][+workspace/delete]]               |
| ~SPC TAB l~   | [[#4057c04d-8f84-4e26-833d-0fa1aa3a9f04][+workspace/load]]                 |
| ~SPC TAB n~   | [[#695472c7-79ff-4266-bb7d-b1485e59d74e][+workspace/new]]                  |
| ~SPC TAB r~   | [[#941fe096-93f4-469a-afc0-62c495240252][+workspace/rename]]               |
| ~SPC TAB s~   | [[#03cf9a7a-c3b9-45b0-b65c-f2f496fbd2a1][+workspace/save]]                 |
| ~SPC TAB x~   | [[#890c2e11-73ad-476b-943b-80d45620b30d][+workspace/kill-session]]         |
| ~SPC TAB TAB~ | [[#9c3ba37e-2aa1-4408-83ed-9089f39d40b5][+workspace/display]]              |
** SPC / 
#+NAME: SPC/
| Key       | Command                  |
|-----------+--------------------------|
| ~SPC / b~ | [[#165c441e-ab52-4517-a695-7b4f27607f6a][swiper]]                   |
| ~SPC / d~ | [[#324c326d-b46b-41aa-bc49-a9e9f177d8c6][+default/search-from-cwd]] |
| ~SPC / i~ | [[#5acde342-4342-4312-b7f7-a44b21b78e76][imenu]]                    |
| ~SPC / l~ | [[#57ca7975-ea47-4837-bf4b-89e518b492d2][ace-link]]                 |
| ~SPC / o~ | [[#7a257daa-ac79-4bb5-9b2c-c02c724ef3a2][+lookup/online-select]]    |
| ~SPC / p~ | [[#7858ddc8-826c-4d30-99f7-02c347dca907][+default/search-project]]  |
| ~SPC / I~ | [[#e7441417-829b-45dd-a34e-a2b23b4df931][imenu-anywhere]]           |
** SPC h 
#+NAME: SPCh
| Key            | Command                          |
|----------------+----------------------------------|
| ~SPC h C-c~    | [[#a759054d-fed2-48b8-99dc-dee8abd658f2][describe-coding-system]]           |
| ~SPC h C-d~    | [[#1222b38b-ca0f-40a8-941c-60057984b52b][view-emacs-debugging]]             |
| ~SPC h C-e~    | [[#e7b872d0-441e-43c2-a74e-351ad408a32b][view-external-packages]]           |
| ~SPC h C-f~    | [[#a054e492-e31f-4310-a53e-d3eff80a0a7e][view-emacs-FAQ]]                   |
| ~SPC h C-h~    | [[#9295daa6-561a-48d1-8ff4-17753c11b9e3][help-for-help]]                    |
| ~SPC h C-k~    | [[#2d76f838-070b-47ea-a28a-edacf595d841][describe-key-briefly]]             |
| ~SPC h C-l~    | [[#48b97c49-0a89-41c8-af0f-30a1c2cdc02d][describe-language-environment]]    |
| ~SPC h RET~    | [[#260569d7-34b8-4ba3-9061-2445b752d90b][info-emacs-manual]]                |
| ~SPC h C-n~    | [[#23d24549-95b8-407a-86b1-6235f2c06ed2][view-emacs-news]]                  |
| ~SPC h C-o~    | [[#93f1eb32-2d90-4822-96fe-d6e5b75840d7][describe-distribution]]            |
| ~SPC h C-p~    | [[#e079a9b1-b3b1-4924-9923-cdaff4047908][view-emacs-problems]]              |
| ~SPC h C-s~    | [[#d195498e-6e80-413d-8cee-3f890b06cb7e][search-forward-help-for-help]]     |
| ~SPC h C-t~    | [[#bff59c71-b309-4e15-bb83-75c43e3be1f5][view-emacs-todo]]                  |
| ~SPC h C-v~    | [[#ce608d29-9a41-4a5e-8604-ff46449046c2][doom/version]]                     |
| ~SPC h C-w~    | [[#e59eba1c-3b37-4009-96b2-414b16c61a8b][describe-no-warranty]]             |
| ~SPC h C-\~    | [[#70a7bf65-2854-4548-b31b-e1103c54876e][describe-input-method]]            |
| ~SPC h '~      | [[#5de27659-5aeb-489c-94cf-054ca5d232e8][describe-char]]                    |
| ~SPC h .~      | [[#bd0eabce-e5e0-43e4-b020-a2441e62bda2][display-local-help]]               |
| ~SPC h ?~      | [[#371dbf06-f937-44a9-940c-a45ded2d2e7c][help-for-help]]                    |
| ~SPC h A~      | [[#2370416e-7eb8-4587-9042-e9b51a52abbe][doom/describe-autodefs]]           |
| ~SPC h B~      | [[#84e4991a-b693-4526-b154-546fb67457cd][doom/open-bug-report]]             |
| ~SPC h C~      | [[#a0810758-274c-421b-bc35-a7300662e14b][describe-coding-system]]           |
| ~SPC h D~      | [[#c7542ba0-0002-40b9-818b-53e4dec59778][doom/open-manual]]                 |
| ~SPC h E~      | [[#779869f2-7f6c-4a16-a562-a6e3df299811][doom/open-vanilla-sandbox]]        |
| ~SPC h F~      | [[#30cc556b-c111-4334-9e60-4a8d924242d0][describe-face]]                    |
| ~SPC h I~      | [[#b9e9e349-815b-4d79-9249-30c207a876df][describe-input-method]]            |
| ~SPC h K~      | [[#5f89992d-e664-493c-a16e-a2910130f3f4][Info-goto-emacs-key-command-node]] |
| ~SPC h L~      | [[#b666eebf-22a1-4b08-a559-6b4962265e6e][global-command-log-mode]]          |
| ~SPC h M~      | [[#e020580f-8090-416a-bd42-6e52a71ad1eb][doom/describe-active-minor-mode]]  |
| ~SPC h O~      | [[#aba46802-da35-4223-baca-97b822056462][+lookup/online]]                   |
| ~SPC h P~      | [[#e05bdc27-1f3c-4e29-936e-777e1c22af23][find-library]]                     |
| ~SPC h S~      | [[#e6b3fad8-a4d5-46ff-ba77-caeff9b35327][info-lookup-symbol]]               |
| ~SPC h T~      | [[#e5151b05-cb18-4328-a7a9-f183a0c0e3b7][doom/toggle-profiler]]             |
| ~SPC h V~      | [[#195ae8b3-fd61-4e8f-8a3b-08afc3e3c2e9][set-variable]]                     |
| ~SPC h W~      | [[#556e6136-bce5-46aa-a860-e719ef570ddf][+default/man-or-woman]]            |
| ~SPC h a~      | [[#8f341881-a381-42b8-9090-2dbd958b967f][apropos]]                          |
| ~SPC h b~      | [[#f6c6cd82-00bf-4832-9d2d-f5724b3a809b][describe-bindings]]                |
| ~SPC h c~      | [[#d8834fbe-cb3f-4725-8760-cc1a60a0a027][describe-key-briefly]]             |
| ~SPC h d~      | [[#a1bbf15e-1023-4453-b90a-6fffde357950][doom/describe-module]]             |
| ~SPC h e~      | [[#815de66f-6791-49d8-bed9-639a969dccd7][view-echo-area-messages]]          |
| ~SPC h f~      | [[#ff3bdf04-c0e5-4a64-996b-261a2514dfc7][describe-function]]                |
| ~SPC h g~      | [[#c4a4b76b-2d8e-4f2d-a1b5-43ab554b7a78][describe-gnu-project]]             |
| ~SPC h h~      | [[#045b0a92-3056-4b04-9993-7160f865946d][doom/describe-symbol]]             |
| ~SPC h i~      | [[#5ed2e118-29e0-45b3-8619-96c0f8fc7643][info]]                             |
| ~SPC h k~      | [[#fdae618f-12bd-4d91-acef-d77ba08861ca][describe-key]]                     |
| ~SPC h l~      | [[#1f20349f-bc75-43d5-b03b-ff0fd9c7ee29][view-lossage]]                     |
| ~SPC h m~      | [[#2b2f0e9c-f808-4907-adad-8c54601ad61d][describe-mode]]                    |
| ~SPC h n~      | [[#04d9248e-407d-4bb5-86ce-82a3a0f9bfeb][doom/open-news]]                   |
| ~SPC h o~      | [[#dd3d9a7c-a09b-4f92-afd7-8f215799ccee][describe-symbol]]                  |
| ~SPC h p~      | [[#a8ec95ce-a969-44b4-9968-38e946b9aeef][doom/describe-package]]            |
| ~SPC h q~      | [[#411fe133-4f1f-47d5-8159-932c1da1a3b2][help-quit]]                        |
| ~SPC h s~      | [[#a5e5a1c1-ec70-43bb-b4ec-85ad07025432][describe-syntax]]                  |
| ~SPC h t~      | [[#914642f8-4c80-49ab-8573-57b29753483d][help-with-tutorial]]               |
| ~SPC h v~      | [[#0d568527-aeee-4be1-8f2e-af0546a767ce][describe-variable]]                |
| ~SPC h w~      | [[#008720ad-b460-43af-979f-de54809b32e9][where-is]]                         |
| ~SPC h <f1>~   | [[#2477f569-77c8-487d-b97c-4c78e618095f][help-for-help]]                    |
| ~SPC h <help>~ | [[#590fed02-1350-4d6e-b3d6-f2672df8e23b][help-for-help]]                    |
| ~SPC h C-a~    | [[#8bd28223-356f-43cf-9b8c-6122b92c8932][about-emacs]]                      |
** SPC w 
#+NAME: SPCw
| Key           | Command                              |   |
|---------------+--------------------------------------+---|
| ~SPC w C-c~   | [[#9846b162-0b1d-4ba1-a766-892e9e16f0a2][ace-delete-window]]                    |   |
| ~SPC w C-f~   | [[#b4281713-c994-4f35-8d31-9fdebb2321cb][ffap-other-window]]                    |   |
| ~SPC w C-h~   | [[#5bddd09b-cbc1-4286-bc39-520eadb9ee34][evil-window-left]]                     |   |
| ~SPC w C-j~   | [[#23d27428-7864-49b4-be79-9aa8de38a6ea][evil-window-down]]                     |   |
| ~SPC w C-k~   | [[#91a3a7dd-dbbc-4aad-9bfc-99990d23a23e][evil-window-up]]                       |   |
| ~SPC w C-l~   | [[#fde5e873-8b63-4dc2-a1c4-741cd4896f2f][evil-window-right]]                    |   |
| ~SPC w C-n~   | [[#4b75e306-cdbf-492f-8270-e6c78be29527][evil-window-new]]                      |   |
| ~SPC w C-o~   | [[#45307f29-ec24-461e-8637-a38ca19e2bbc][delete-other-windows]]                 |   |
| ~SPC w C-p~   | [[#e64d75a3-1342-4fa9-8789-a683ae3452ce][evil-window-mru]]                      |   |
| ~SPC w C-r~   | [[#c0a158ff-345a-452c-965a-e2eb728aa2a4][winner-redo]]                          |   |
| ~SPC w C-s~   | [[#9a602505-f297-41ca-9db2-c4b43902af67][evil-window-split]]                    |   |
| ~SPC w C-t~   | [[#0ac38de5-362f-44c9-bab0-2fc353f3a1d1][evil-window-top-left]]                 |   |
| ~SPC w C-u~   | [[#bdda68e8-251c-4cc2-a6fd-2d18b11cfadc][winner-undo]]                          |   |
| ~SPC w C-v~   | [[#b87a0553-ef86-4ae0-9b32-7a4049350672][evil-window-vsplit]]                   |   |
| ~SPC w C-w~   | [[#4b1e0a50-27aa-48f0-97b6-0db3f8f49d84][other-window]]                         |   |
| ~SPC w C-_~   | [[#df103e24-1b91-4a2a-a4f7-1501608fdd40][evil-window-set-height]]               |   |
| ~SPC w +~     | [[#2346830e-36ce-4a00-87fc-cc0168f50473][evil-window-increase-height]]          |   |
| ~SPC w -~     | [[#4fafdd2d-8e63-4b7d-b9e2-435cf23e0498][evil-window-decrease-height]]          |   |
| ~SPC w <~     | [[#c22a7020-bbc2-4f85-8efc-5f3fede855c4][evil-window-decrease-width]]           |   |
| ~SPC w =~     | [[#8da312f5-88c3-46ea-9277-fd0bae076ccf][balance-windows]]                      |   |
| ~SPC w >~     | [[#55c87fe1-ebdb-4d7d-83f8-d88870683110][evil-window-increase-width]]           |   |
| ~SPC w H~     | [[#c9da10ce-88c6-4544-8ec1-916c2b82b654][+evil/window-move-left]]               |   |
| ~SPC w J~     | [[#a3440c3e-9040-47c7-a1b1-a1d3e050715f][+evil/window-move-down]]               |   |
| ~SPC w K~     | [[#01d260c9-baed-4271-9d70-b5375d1e36b5][+evil/window-move-up]]                 |   |
| ~SPC w L~     | [[#ddcb4ab9-ea51-4d63-b468-b96c4cc071af][+evil/window-move-right]]              |   |
| ~SPC w O~     | [[#42e64077-74c7-4394-a9ea-644d10336b11][doom/window-zoom]]                     |   |
| ~SPC w R~     | [[#480fadd5-d18a-4558-ae87-ad7cffe9e98f][evil-window-rotate-upwards]]           |   |
| ~SPC w S~     | [[#f212ee90-3ec2-4b26-87ca-73ee05d5962a][evil-window-split]]                    |   |
| ~SPC w W~     | [[#9d2962d2-055d-4031-9258-3d24f3c28154][evil-window-prev]]                     |   |
| ~SPC w _~     | [[#3b93c8cf-1d66-4c47-9309-6482f34d884f][evil-window-set-height]]               |   |
| ~SPC w b~     | [[#b3d4402a-1b58-4f12-884e-726a4f34e8d7][evil-window-bottom-right]]             |   |
| ~SPC w c~     | [[#537bc383-a1b3-4bc9-b370-c171846c1e8e][+workspace/close-window-or-workspace]] |   |
| ~SPC w h~     | [[#9f8d7465-2730-46bc-aecc-e66ce3f54ba6][evil-window-left]]                     |   |
| ~SPC w j~     | [[#8942711b-463d-44f0-ae1d-25e6e3c4b552][evil-window-down]]                     |   |
| ~SPC w k~     | [[#36d4d244-9c84-4a03-b77a-c5573183be5b][evil-window-up]]                       |   |
| ~SPC w l~     | [[#87ea4869-4cca-4d1e-b776-68cbafebf11d][evil-window-right]]                    |   |
| ~SPC w n~     | [[#798368f5-b3b5-40f2-8532-428e83cc328b][evil-window-new]]                      |   |
| ~SPC w o~     | [[#c3ee1228-7bd5-4caf-b9fb-536b557aeeae][doom/window-enlargen]]                 |   |
| ~SPC w p~     | [[#ad87cc70-aace-435e-891d-bf1741aec654][evil-window-mru]]                      |   |
| ~SPC w q~     | [[#fe3377ad-1cc2-4369-88aa-81cfc01adfe7][evil-quit]]                            |   |
| ~SPC w r~     | [[#46e648bd-ba31-4706-81ad-45f76e385e98][evil-window-rotate-downwards]]         |   |
| ~SPC w s~     | [[#77f8324e-8b68-49b5-af98-ffca2d83f80c][evil-window-split]]                    |   |
| ~SPC w t~     | [[#1642cbef-e2b0-44e1-a4f5-d908b5768698][evil-window-top-left]]                 |   |
| ~SPC w u~     | [[#be04a0ed-bed5-4198-9eb9-a2b4986ea012][winner-undo]]                          |   |
| ~SPC w v~     | [[#fe3b666d-1baa-4e7e-a578-503c303b16d9][evil-window-vsplit]]                   |   |
| ~SPC w w~     | [[#eee43689-5cfe-4e1c-b701-6135193b35f5][evil-window-next]]                     |   |
| ~SPC w        | [[#10cf43ab-675d-4722-8ce3-3486a50885a3][evil-window-set-width]]~               |   |
| ~SPC w C-S-h~ | [[#f2ad9ebd-e051-4c64-bafa-bd09e069c8f1][evil-window-move-far-left]]            |   |
| ~SPC w C-S-j~ | [[#3694f5a2-9d09-4163-bf69-0450db285c6b][evil-window-move-very-bottom]]         |   |
| ~SPC w C-S-k~ | [[#4d514dd3-2cc6-46c7-a71b-8c34822f75f5][evil-window-move-very-top]]            |   |
| ~SPC w C-S-l~ | [[#addaa83b-5a3b-4ab2-a3ac-066212bfab22][evil-window-move-far-right]]           |   |
| ~SPC w C-S-r~ | [[#d6e54d0b-287a-4190-b46b-bd3b989cee1b][evil-window-rotate-upwards]]           |   |
| ~SPC w C-S-s~ | [[#dda0bf3d-25cc-4983-a60d-9fcc312c77c0][evil-window-split]]                    |   |
| ~SPC w C-S-w~ | [[#9d756624-ff89-4e42-8b3e-d59209a4f1dc][ace-swap-window]]                      |   |
| ~SPC w C-b~   | [[#5af6b7fa-695d-4f38-992d-38e0428063f2][evil-window-bottom-right]]             |   |
** SPC o 
#+NAME: SPCo
| Key         | Command         |
|-------------+-----------------|
| ~SPC o a m~ | [[#8f20b935-6658-4287-ae92-95380361a784][org-tags-view]]   |
| ~SPC o a t~ | [[#57555522-56af-4599-b847-b3cf2083a60f][org-todo-list]]   |
| ~SPC o a v~ | [[#31217721-9d95-4426-868a-89e41eb23a57][org-search-view]] |
| ~SPC o a a~ | [[#d0864d70-7e7a-47ad-ae7a-40bf6e38a8bc][org-agenda]]      |
** SPC g 
#+NAME: SPCg
| Key         | Command                       |
|-------------+-------------------------------|
| ~SPC g c c~ | [[#cd606ac1-b327-48b0-bafe-8012d1227fec][magit-commit-create]]           |
| ~SPC g c i~ | [[#7328b26c-a017-4b3a-9ba7-f5abb2ac8912][forge-create-issue]]            |
| ~SPC g c p~ | [[#8174ba6d-e053-43f4-b59e-db7a536b9ef0][forge-create-pullreq]]          |
| ~SPC g c r~ | [[#14b3e79b-af58-4a94-b85a-a42d89b17109][magit-init]]                    |
| ~SPC g l i~ | [[#57108eb1-8c65-4514-8211-197ce2073ce4][forge-list-issues]]             |
| ~SPC g l n~ | [[#225709e5-83cf-4fe7-abab-c73cabb553e6][forge-list-notifications]]      |
| ~SPC g l p~ | [[#6d9dec9e-4db2-4a8d-8ef1-2186c2ec5a04][forge-list-pullreqs]]           |
| ~SPC g l r~ | [[#c7759972-c993-43fd-b6b7-4838d893a77c][magit-list-repositories]]       |
| ~SPC g l s~ | [[#cfb7c996-8c12-4be2-a188-fb7090d22bfb][magit-list-submodules]]         |
| ~SPC g o .~ | [[#ccd9bb82-35f7-4118-81c2-3c19f31ba507][+vc/git-browse-region-or-line]] |
| ~SPC g o I~ | [[#452e1ee3-94c6-4892-baa0-e3cbf083d955][forge-browse-issues]]           |
| ~SPC g o P~ | [[#43243d71-5c54-46c3-b51f-d2f4d2f114fc][forge-browse-pullreqs]]         |
| ~SPC g o c~ | [[#e6637c74-9087-4cbb-8279-a665ec21b62e][forge-browse-commit]]           |
| ~SPC g o i~ | [[#6aa421fa-afbc-4b9b-b097-496d49c1109e][forge-browse-issue]]            |
| ~SPC g o p~ | [[#5dcfbdcb-3156-4226-925d-437b0eddb41b][forge-browse-pullreq]]          |
| ~SPC g o r~ | [[#182c0b40-a9e2-4236-a89a-3ac64bb48fc3][forge-browse-remote]]           |
| ~SPC g f c~ | [[#6b7a629d-6bf6-4a76-965d-4066280988c5][magit-show-commit]]             |
| ~SPC g f f~ | [[#86f5d314-2e50-4f2e-8500-c78b780fc00e][magit-find-file]]               |
| ~SPC g f g~ | [[#077c5d67-8fa3-48fc-a08b-744b8c2beb0e][magit-find-git-config-file]]    |
| ~SPC g f i~ | [[#5958338c-bf28-46bc-b0c0-b137fc9d5082][forge-visit-issue]]             |
| ~SPC g f p~ | [[#d32a6b0c-f2f5-468b-b26d-88a717f753c9][forge-visit-pullreq]]           |
| ~SPC g c R~ | [[#f4be7cde-5467-4e39-8c00-35dbd343b790][+magit/clone]]                  |
** SPC h 
#+NAME: SPCh
| Key         | Command              |
|-------------+----------------------|
| ~SPC h r f~ | [[#21d92b57-2205-4dbb-886a-f3336695a92b][doom/reload-font]]     |
| ~SPC h r p~ | [[#94759093-d634-4121-8011-53a323c3d8e6][doom/reload-packages]] |
| ~SPC h r r~ | [[#eccc3764-d1ea-4c9f-8948-a5e69b287d66][doom/reload]]          |
| ~SPC h r t~ | [[#3bf5d7ff-8496-4e36-985f-a36310f6d6f2][doom/reload-theme]]    |
| ~SPC h 4 i~ | [[#c128a286-6e89-4174-8b91-048dc1c9cb73][info-other-window]]    |
| ~SPC h r P~ | [[#2201b894-1e0e-4dd4-987e-4e65685d6749][doom/reload-project]]  |
** SPC m 
#+NAME: SPCm
| Key           | Command                              |
|---------------+--------------------------------------|
| ~SPC m b~     | [[#cca6a822-c3c5-4ec6-9595-3eb1cf9208eb][org-switchb]]                          |
| ~SPC m d~     | [[#1045bdf1-ac13-43ad-a5f5-b067b440cfb8][org-deadline]]                         |
| ~SPC m l~     | [[#5be3b6e9-d8a5-4b9a-80f0-6a2103a8ed84][org-store-link]]                       |
| ~SPC m t~     | [[#8aa0c3b4-fbf6-43e5-892e-fc119f243145][org-todo]]                             |
| ~SPC m e M~   | [[#8cc8ffb0-da2a-41ff-831b-5f07bbb91f8a][org-md-export-as-markdown]]            |
| ~SPC m e R~   | [[#29a2cc23-01b8-4421-9bbb-4bc7de5f2893][org-reveal-export-to-html-and-browse]] |
| ~SPC m e m~   | [[#3c5332fa-b591-4632-99c6-a23c5610f214][org-md-export-to-markdown]]            |
| ~SPC m e r~   | [[#de0c9d8a-5112-4598-ad5b-2a418024d98f][org-reveal-export-to-html]]            |
| ~SPC m c C~   | [[#76eda266-e262-44da-b736-d3c0fc02c453][org-clock-out]]                        |
| ~SPC m c c~   | [[#c2b90f65-f0c4-4f62-9049-a567a28b66db][org-clock-in]]                         |
| ~SPC m c g~   | [[#02bdcf39-e46e-47a3-b7be-afab6bca2b06][org-clock-goto]]                       |
| ~SPC m c x~   | [[#f0aaaacc-fc23-46b0-8f0a-bcbaf226df82][org-clock-cancel]]                     |
| ~SPC m e b L~ | [[#e041a4d0-bdcf-4ff8-8081-ce4bed7eb304][org-beamer-export-as-latex]]           |
| ~SPC m e b l~ | [[#9e5b67be-850d-491d-8b45-a9e30d289ed9][org-beamer-export-to-latex]]           |
| ~SPC m e b p~ | [[#e26eee8c-b4e3-40bd-81ea-69910c34fd8d][org-beamer-export-to-pdf]]             |
| ~SPC m T~     | [[#7db925a0-16fd-4a34-9dc8-31db11e253fe][org-todo-list]]                        |

* Documentation
:PROPERTIES:
:CUSTOM_ID: DOCUMENTATION
:END:
** SPC RET
:PROPERTIES:
:CUSTOM_ID: 7936b19a-9919-4a32-807c-ecf9dd289a82
:END:
*** Function
*bookmark-jump*
*** Documentation
Jump to bookmark BOOKMARK (a point in some file).
You may have a problem using this function if the value of variable
‘bookmark-alist’ is nil.  If that happens, you need to load in some
bookmarks.  See help on function ‘bookmark-load’ for more about
this.

If the file pointed to by BOOKMARK no longer exists, you will be asked
if you wish to give the bookmark a new location, and ‘bookmark-jump’
will then jump to the new location, as well as recording it in place
of the old one in the permanent bookmark record.

BOOKMARK is usually a bookmark name (a string).  It can also be a
bookmark record, but this is usually only done by programmatic callers.

If DISPLAY-FUNC is non-nil, it is a function to invoke to display the
bookmark.  It defaults to ‘pop-to-buffer-same-window’.  A typical value for
DISPLAY-FUNC would be ‘switch-to-buffer-other-window’.
** SPC SPC
:PROPERTIES:
:CUSTOM_ID: 4713167e-f20a-4651-890d-3f92c3a79651
:END:
*** Function
*projectile-find-file*
*** Documentation
Jump to a project’s file using completion.
With a prefix arg INVALIDATE-CACHE invalidates the cache first.

(fn &optional INVALIDATE-CACHE)
** SPC '
:PROPERTIES:
:CUSTOM_ID: c8a625ed-3383-4f8a-bd85-35fb950a75e1
:END:
*** Function
*ivy-resume*
*** Documentation
Resume the last completion session.
** SPC ,
:PROPERTIES:
:CUSTOM_ID: d16eacde-6905-4cd9-835d-ba3953329aee
:END:
*** Function
*persp-switch-to-buffer*
*** Documentation
Switch to buffer, read buffer with restriction to current perspective.
** SPC .
:PROPERTIES:
:CUSTOM_ID: 39ec3fd1-540f-4560-8e87-be4b99176816
:END:
*** Function
*find-file*
*** Documentation
Edit file FILENAME.
Switch to a buffer visiting file FILENAME,
creating one if none already exists.
Interactively, the default if you just type RET is the current directory,
but the visited file name is available through the minibuffer history:
type M-x next-history-element to pull it into the minibuffer.

The first time M-x next-history-element is used after Emacs prompts for
the file name, the result is affected by ‘file-name-at-point-functions’,
which by default try to guess the file name by looking at point in the
current buffer.  Customize the value of ‘file-name-at-point-functions’
or set it to nil, if you want only the visited file name and the
current directory to be available on first M-x next-history-element
request.

You can visit files on remote machines by specifying something
like /ssh:SOME_REMOTE_MACHINE:FILE for the file name.  You can
also visit local files as a different user by specifying
/sudo::FILE for the file name.
See the Info node ‘(tramp)File name Syntax’ in the Tramp Info
manual, for more about this.

Interactively, or if WILDCARDS is non-nil in a call from Lisp,
expand wildcards (if any) and visit multiple files.  You can
suppress wildcard expansion by setting ‘find-file-wildcards’ to nil.

To visit a file without any kind of conversion and without
automatically choosing a major mode, use M-x find-file-literally.

(fn FILENAME &optional WILDCARDS)
** SPC :
:PROPERTIES:
:CUSTOM_ID: ad1749ea-3bed-4e19-98e3-970347cf0283
:END:
*** Function
*execute-extended-command*
*** Documentation
Read a command name, then read the arguments and call the command.
To pass a prefix argument to the command you are
invoking, give a prefix argument to ‘execute-extended-command’.

(fn PREFIXARG &optional COMMAND-NAME TYPED)
** SPC ;
:PROPERTIES:
:CUSTOM_ID: c224b829-388d-45df-b6bd-19f844e45bef
:END:
*** Function
*eval-expression*
*** Documentation
:after advice: ‘amx-post-eval-force-update’

Evaluate EXP and print value in the echo area.
When called interactively, read an Emacs Lisp expression and
evaluate it.  Value is also consed on to front of the variable
‘values’.  Optional argument INSERT-VALUE non-nil (interactively,
with a non ‘-’ prefix argument) means insert the result into the
current buffer instead of printing it in the echo area.

Normally, this function truncates long output according to the
value of the variables ‘eval-expression-print-length’ and
‘eval-expression-print-level’.  When NO-TRUNCATE is
non-nil (interactively, with a prefix argument of zero), however,
there is no such truncation.

If the resulting value is an integer, and CHAR-PRINT-LIMIT is
non-nil (interactively, unless given a non-zero prefix argument)
it will be printed in several additional formats (octal,
hexadecimal, and character).  The character format is only used
if the value is below CHAR-PRINT-LIMIT (interactively, if the
prefix argument is -1 or the value doesn’t exceed
‘eval-expression-print-maximum-character’).

Runs the hook ‘eval-expression-minibuffer-setup-hook’ on entering the
minibuffer.

If ‘eval-expression-debug-on-error’ is non-nil, which is the default,
this command arranges for all errors to enter the debugger.

(fn EXP &optional INSERT-VALUE NO-TRUNCATE CHAR-PRINT-LIMIT)
** SPC <
:PROPERTIES:
:CUSTOM_ID: 71111500-75ee-4a40-aa12-0a2926cb1271
:END:
*** Function
*switch-to-buffer*
*** Documentation
:around advice: ‘ad-Advice-switch-to-buffer’
:around advice: ‘doom*run-switch-buffer-hooks’

Display buffer BUFFER-OR-NAME in the selected window.

WARNING: This is NOT the way to work on another buffer temporarily
within a Lisp program!  Use ‘set-buffer’ instead.  That avoids
messing with the window-buffer correspondences.

If the selected window cannot display the specified buffer
because it is a minibuffer window or strongly dedicated to
another buffer, call ‘pop-to-buffer’ to select the buffer in
another window.  In interactive use, if the selected window is
strongly dedicated to its buffer, the value of the option
‘switch-to-buffer-in-dedicated-window’ specifies how to proceed.

If called interactively, read the buffer name using ‘read-buffer’.
The variable ‘confirm-nonexistent-file-or-buffer’ determines
whether to request confirmation before creating a new buffer.
See ‘read-buffer’ for features related to input and completion
of buffer names.

BUFFER-OR-NAME may be a buffer, a string (a buffer name), or nil.
If BUFFER-OR-NAME is a string that does not identify an existing
buffer, create a buffer with that name.  If BUFFER-OR-NAME is
nil, switch to the buffer returned by ‘other-buffer’.

If optional argument NORECORD is non-nil, do not put the buffer
at the front of the buffer list, and do not make the window
displaying it the most recently selected one.

If optional argument FORCE-SAME-WINDOW is non-nil, the buffer
must be displayed in the selected window when called
non-interactively; if that is impossible, signal an error rather
than calling ‘pop-to-buffer’.  It has no effect when the option
‘switch-to-buffer-obey-display-actions’ is non-nil.

The option ‘switch-to-buffer-preserve-window-point’ can be used
to make the buffer appear at its last position in the selected
window.

If the option ‘switch-to-buffer-obey-display-actions’ is non-nil,
run the function ‘pop-to-buffer-same-window’ instead.
This may display the buffer in another window as specified by
‘display-buffer-overriding-action’, ‘display-buffer-alist’ and
other display related variables.  If this results in displaying
the buffer in the selected window, window start and point are adjusted
as prescribed by the option ‘switch-to-buffer-preserve-window-point’.
Otherwise, these are left alone.

Return the buffer switched to.

(fn BUFFER-OR-NAME &optional NORECORD FORCE-SAME-WINDOW)
** SPC X
:PROPERTIES:
:CUSTOM_ID: 006737f1-ad10-4cf4-bccf-c1e66bd3cdad
:END:
*** Function
*org-capture*
*** Documentation
Capture something.

This will let you select a template from ‘org-capture-templates’, and
then file the newly captured information.  The text is immediately
inserted at the target location, and an indirect buffer is shown where
you can edit it.  Pressing ‘C-c C-c’ brings you back to the previous
state of Emacs, so that you can continue your work.

When called interactively with a ‘M-x universal-argument’ prefix argument GOTO, don’t
capture anything, just go to the file/headline where the selected
template stores its notes.

With a ‘M-x universal-argument M-x universal-argument’ prefix argument, go to the last note stored.

When called with a ‘C-0’ (zero) prefix, insert a template at point.

When called with a ‘C-1’ (one) prefix, force prompting for a date when
a datetree entry is made.

ELisp programs can set KEYS to a string associated with a template
in ‘org-capture-templates’.  In this case, interactive selection
will be bypassed.

If ‘org-capture-use-agenda-date’ is non-nil, capturing from the
agenda will use the date at point as the default date.  Then, a
‘C-1’ prefix will tell the capture process to use the HH:MM time
of the day at point (if any) or the current HH:MM time.

(fn &optional GOTO KEYS)
** SPC u
:PROPERTIES:
:CUSTOM_ID: e1cccaea-a301-44c5-8ca4-6bff866b22ea
:END:
*** Function
*universal-argument*
*** Documentation
Begin a numeric argument for the following command.
Digits or minus sign following SPC u make up the numeric argument.
SPC u following the digits or minus sign ends the argument.
SPC u without digits or minus sign provides 4 as argument.
Repeating SPC u without digits or minus sign
 multiplies the argument by 4 each time.
For some commands, just SPC u by itself serves as a flag
which is different in effect from any particular numeric argument.
These commands include C-@ and M-x start-kbd-macro.
** SPC x
:PROPERTIES:
:CUSTOM_ID: 8c7db950-b793-45e0-8101-7ee41ff11c92
:END:
*** Function
*doom/open-scratch-buffer*
*** Documentation
Opens a scratch pad window in the same major-mode.

If ARG (universal argument), then open a persistent scratch pad buffer. You’ll
be prompted for its name, or to open a previously created. These are stored in
‘doom-scratch-files-dir’.

If a region is active, copy its contents to the scratch pad.
** SPC ~
:PROPERTIES:
:CUSTOM_ID: b6d4765b-9eb8-41f6-a3a9-2db456b42e37
:END:
*** Function
*+popup/toggle*
*** Documentation
If popups are open, close them. If they aren’t, restore the last one or open
the message buffer in a popup window.
** SPC DEL
:PROPERTIES:
:CUSTOM_ID: f110201c-49d0-4041-806b-84072bee6352
:END:
*** Function
*+nav-flash/blink-cursor*
*** Documentation
Blink current line using ‘nav-flash’.
** SPC t F
:PROPERTIES:
:CUSTOM_ID: 0f780fa8-2f15-4077-9934-57fc3e8f0898
:END:
*** Function
*toggle-frame-fullscreen*
*** Documentation
Toggle fullscreen state of FRAME.
Make selected frame fullscreen or restore its previous size
if it is already fullscreen.

Before making the frame fullscreen remember the current value of
the frame’s ‘fullscreen’ parameter in the ‘fullscreen-restore’
parameter of the frame.  That value is used to restore the
frame’s fullscreen state when toggling fullscreen the next time.

Note that with some window managers you may have to set
‘frame-resize-pixelwise’ to non-nil in order to make a frame
appear truly fullscreen.  In addition, you may have to set
‘x-frame-normalize-before-maximize’ in order to enable
transitions from one fullscreen state to another.

See also ‘toggle-frame-maximized’.

(fn &optional FRAME)
** SPC t b
:PROPERTIES:
:CUSTOM_ID: 7877ad19-4225-4137-b37f-b3fb6d445cd0
:END:
*** Function
*doom-big-font-mode*
*** Documentation
A global mode that resizes the font, for streams, screen-sharing and
presentations.

If called interactively, enable Doom-Big-Font mode if ARG is positive, and
disable it if ARG is zero or negative.  If called from Lisp,
also enable the mode if ARG is omitted or nil, and toggle it
if ARG is ‘toggle’; disable the mode otherwise.

Uses ‘doom-big-font’ when enabled.
** SPC t f
:PROPERTIES:
:CUSTOM_ID: cf79b310-5340-4cc6-acf3-183d0d6f71f3
:END:
*** Function
*flycheck-mode*
*** Documentation
Minor mode for on-the-fly syntax checking.

When called interactively, toggle ‘flycheck-mode’.  With prefix
ARG, enable ‘flycheck-mode’ if ARG is positive, otherwise disable
it.

When called from Lisp, enable ‘flycheck-mode’ if ARG is omitted,
nil or positive.  If ARG is ‘toggle’, toggle ‘flycheck-mode’.
Otherwise behave as if called interactively.

In ‘flycheck-mode’ the buffer is automatically syntax-checked
using the first suitable syntax checker from ‘flycheck-checkers’.
Use ‘flycheck-select-checker’ to select a checker for the current
buffer manually.

key             binding
---             -------

C-c             Prefix Command

C-c !           Prefix Command

C-c ! C-c       flycheck-compile
C-c ! C-w       flycheck-copy-errors-as-kill
C-c ! ?         flycheck-describe-checker
C-c ! C         flycheck-clear
C-c ! H         display-local-help
C-c ! V         flycheck-version
C-c ! c         flycheck-buffer
C-c ! e         flycheck-explain-error-at-point
C-c ! h         flycheck-display-error-at-point
C-c ! i         flycheck-manual
C-c ! l         flycheck-list-errors
C-c ! n         flycheck-next-error
C-c ! p         flycheck-previous-error
C-c ! s         flycheck-select-checker
C-c ! v         flycheck-verify-setup
C-c ! x         flycheck-disable-checker



(fn &optional ARG)
** SPC t g
:PROPERTIES:
:CUSTOM_ID: d2f0ecdf-b69d-4918-bec1-993edb3e302b
:END:
*** Function
*evil-goggles-mode*
*** Documentation
evil-goggles global minor mode.

If called interactively, enable Evil-Goggles mode if ARG is positive, and
disable it if ARG is zero or negative.  If called from Lisp,
also enable the mode if ARG is omitted or nil, and toggle it
if ARG is ‘toggle’; disable the mode otherwise.

(fn &optional ARG)
** SPC t l
:PROPERTIES:
:CUSTOM_ID: 90e112e3-64bc-4247-a74b-b4b1da799018
:END:
*** Function
*doom/toggle-line-numbers*
*** Documentation
Toggle line numbers.

Cycles through regular, relative and no line numbers. The order depends on what
‘display-line-numbers-type’ is set to. If you’re using Emacs 26+, and
visual-line-mode is on, this skips relative and uses visual instead.

See ‘display-line-numbers’ for what these values mean.
** SPC t p
:PROPERTIES:
:CUSTOM_ID: 3ead99f5-ba3d-47bf-a795-02272a000b6a
:END:
*** Function
*+org-present/start*
*** Documentation
TODO

(fn)
** SPC t s
:PROPERTIES:
:CUSTOM_ID: 090e14b7-ab60-42dd-8511-1c7656e87166
:END:
*** Function
*flyspell-mode*
*** Documentation
Toggle on-the-fly spell checking (Flyspell mode).

If called interactively, enable Flyspell mode if ARG is positive, and
disable it if ARG is zero or negative.  If called from Lisp,
also enable the mode if ARG is omitted or nil, and toggle it
if ARG is ‘toggle’; disable the mode otherwise.

Flyspell mode is a buffer-local minor mode.  When enabled, it
spawns a single Ispell process and checks each word.  The default
flyspell behavior is to highlight incorrect words.

Bindings:
z =: correct words (using Ispell).
M-x flyspell-auto-correct-word: automatically correct word.
M-x flyspell-auto-correct-previous-word: automatically correct the last misspelled word.
M-x flyspell-correct-word (or down-mouse-2): popup correct words.

Hooks:
This runs ‘flyspell-mode-hook’ after flyspell mode is entered or exit.

Remark:
‘flyspell-mode’ uses ‘ispell-mode’.  Thus all Ispell options are
valid.  For instance, a different dictionary can be used by
invoking ‘ispell-change-dictionary’.

Consider using the ‘ispell-parser’ to check your text.  For instance
consider adding:
(add-hook 'tex-mode-hook (function (lambda () (setq ispell-parser 'tex))))
in your init file.

M-x flyspell-region checks all words inside a region.
M-x flyspell-buffer checks the whole buffer.

(fn &optional ARG)
** SPC s /
:PROPERTIES:
:CUSTOM_ID: 113b6660-4c14-446d-ba44-75e4b9afdfc8
:END:
*** Function
*yas-visit-snippet-file*
*** Documentation
Choose a snippet to edit, selection like ‘yas-insert-snippet’.

Only success if selected snippet was loaded from a file.  Put the
visited file in ‘snippet-mode’.
** SPC s S
:PROPERTIES:
:CUSTOM_ID: 889b267b-7414-4d9c-b4cb-387d4e9a6999
:END:
*** Function
*+snippets/browse*
*** Documentation
TODO

(fn ARG)
** SPC s c
:PROPERTIES:
:CUSTOM_ID: 9d955af1-310d-4784-a1bc-d327e7341781
:END:
*** Function
*aya-create*
*** Documentation
Works on either the current line, or, if ‘mark-active’, the current region.
Removes ‘aya-marker’ prefixes,
writes the corresponding snippet to ‘aya-current’,
with words prefixed by ‘aya-marker’ as fields, and mirrors properly set up.

(fn)
** SPC s e
:PROPERTIES:
:CUSTOM_ID: b9124888-c7c2-4e01-8b0f-a1bc7b0aced9
:END:
*** Function
*aya-expand*
*** Documentation
Insert the last yasnippet created by ‘aya-create’.

(fn)
** SPC s i
:PROPERTIES:
:CUSTOM_ID: d805ed3b-78c5-456a-bae0-4321f8a003cc
:END:
*** Function
*yas-insert-snippet*
*** Documentation
Choose a snippet to expand, pop-up a list of choices according
to ‘yas-prompt-functions’.

With prefix argument NO-CONDITION, bypass filtering of snippets
by condition.
** SPC s n
:PROPERTIES:
:CUSTOM_ID: 4d74ec66-e879-41f4-9163-ea1359c56bba
:END:
*** Function
*yas-new-snippet*
*** Documentation
Pops a new buffer for writing a snippet.

Expands a snippet-writing snippet, unless the optional prefix arg
NO-TEMPLATE is non-nil.
** SPC s r
:PROPERTIES:
:CUSTOM_ID: c3f81cf7-900e-495d-a9a1-436b993c599b
:END:
*** Function
*yas-reload-all*
*** Documentation
Reload all snippets and rebuild the YASnippet menu.

When NO-JIT is non-nil force immediate reload of all known
snippets under ‘yas-snippet-dirs’, otherwise use just-in-time
loading.

When called interactively, use just-in-time loading when given a
prefix argument.
** SPC s s
:PROPERTIES:
:CUSTOM_ID: 9a2dd41f-1e7a-4ec9-a341-e3ddd3404383
:END:
*** Function
*+snippets/find-file*
*** Documentation
TODO

(fn)
** SPC q L
:PROPERTIES:
:CUSTOM_ID: 1a2539cf-159f-4359-9cf6-07201d908303
:END:
*** Function
*doom/load-session*
*** Documentation
TODO

(fn FILE)
** SPC q Q
:PROPERTIES:
:CUSTOM_ID: 9453f505-66e6-4bb3-bda0-728697a281bd
:END:
*** Function
*evil-save-and-quit*
*** Documentation
Save all buffers and exit Emacs.
** SPC q R
:PROPERTIES:
:CUSTOM_ID: c81e453e-0bfc-4a07-a297-bde25a2b1fbb
:END:
*** Function
*doom/restart*
*** Documentation
Restart Emacs.

When called interactively ARGS is interpreted as follows

- with a single ‘universal-argument’ (‘C-u’) Emacs is restarted
  with ‘--debug-init’ flag
- with two ‘universal-argument’ (‘C-u’) Emacs is restarted with
  ‘-Q’ flag
- with three ‘universal-argument’ (‘C-u’) the user prompted for
  the arguments

When called non-interactively ARGS should be a list of arguments
with which Emacs should be restarted.

(fn &optional ARGS)
** SPC q S
:PROPERTIES:
:CUSTOM_ID: 43795568-2f93-4159-813f-a07fbff4cd07
:END:
*** Function
*doom/save-session*
*** Documentation
TODO

(fn FILE)
** SPC q l
:PROPERTIES:
:CUSTOM_ID: cfde721c-2f66-456b-904a-bda350c71f02
:END:
*** Function
*doom/quickload-session*
*** Documentation
TODO

(fn)
** SPC q q
:PROPERTIES:
:CUSTOM_ID: 189958eb-b7bf-45b2-a78a-0821d48e1f52
:END:
*** Function
*evil-quit-all*
*** Documentation
Exits Emacs, asking for saving.
** SPC q r
:PROPERTIES:
:CUSTOM_ID: 9c59ab4b-cda8-4024-9b55-6bdef57e0957
:END:
*** Function
*doom/restart-and-restore*
*** Documentation
TODO

(fn &optional DEBUG)
** SPC q s
:PROPERTIES:
:CUSTOM_ID: 2bff6a9c-08a4-4a62-8ac3-a04cd9f6a04f
:END:
*** Function
*doom/quicksave-session*
*** Documentation
TODO

(fn)
** SPC p !
:PROPERTIES:
:CUSTOM_ID: edc660f7-f5c1-4d10-b263-58b815bee729
:END:
*** Function
*projectile-run-shell-command-in-root*
*** Documentation
Invoke ‘shell-command’ in the project’s root.
** SPC p .
:PROPERTIES:
:CUSTOM_ID: 8adcff30-082b-43ca-9027-c383bb9a961e
:END:
*** Function
*+default/browse-project*
*** Documentation

** SPC p /
:PROPERTIES:
:CUSTOM_ID: 51bd426b-db4d-4b12-a430-e80f4dcbfa85
:END:
*** Function
*projectile-find-file*
*** Documentation
Jump to a project’s file using completion.
With a prefix arg INVALIDATE-CACHE invalidates the cache first.

(fn &optional INVALIDATE-CACHE)
** SPC p c
:PROPERTIES:
:CUSTOM_ID: 47046a75-53c9-4c72-8cf2-3e2db47d816f
:END:
*** Function
*projectile-compile-project*
*** Documentation
Run project compilation command.

Normally you’ll be prompted for a compilation command, unless
variable ‘compilation-read-command’.  You can force the prompt
with a prefix ARG.

(fn ARG)
** SPC p o
:PROPERTIES:
:CUSTOM_ID: 5447c09f-e5eb-4899-a744-d2cebcdf2f57
:END:
*** Function
*projectile-find-other-file*
*** Documentation
Switch between files with the same name but different extensions.
With FLEX-MATCHING, match any file that contains the base name of current file.
Other file extensions can be customized with the variable ‘projectile-other-file-alist’.

(fn &optional FLEX-MATCHING)
** SPC p p
:PROPERTIES:
:CUSTOM_ID: 72b618d1-aea8-4c99-b689-a00c8cc51ab1
:END:
*** Function
*projectile-switch-project*
*** Documentation
Switch to a project we have visited before.
Invokes the command referenced by ‘projectile-switch-project-action’ on switch.
With a prefix ARG invokes ‘projectile-commander’ instead of
‘projectile-switch-project-action.’

(fn &optional ARG)
** SPC p r
:PROPERTIES:
:CUSTOM_ID: 4b91f61d-98cd-40b3-8bf2-39a9354dddb6
:END:
*** Function
*projectile-recentf*
*** Documentation
Show a list of recently visited files in a project.
** SPC p t
:PROPERTIES:
:CUSTOM_ID: 5f2bb02e-35aa-42f5-893f-71e5bfb5091b
:END:
*** Function
*+default/project-tasks*
*** Documentation
Invokes ‘+ivy/tasks’ or ‘+helm/tasks’, depending on which is available.
** SPC p x
:PROPERTIES:
:CUSTOM_ID: 850d3af7-ce60-4799-9fa6-bf3997eb870c
:END:
*** Function
*projectile-invalidate-cache*
*** Documentation
Remove the current project’s files from ‘projectile-projects-cache’.

With a prefix argument PROMPT prompts for the name of the project whose cache
to invalidate.

(fn PROMPT)
** SPC o -
:PROPERTIES:
:CUSTOM_ID: cf15003c-9c45-4044-9a5f-628835450c00
:END:
*** Function
*dired-jump*
*** Documentation
Jump to Dired buffer corresponding to current buffer.
If in a file, Dired the current directory and move to file’s line.
If in Dired already, pop up a level and goto old directory’s line.
In case the proper Dired file line cannot be found, refresh the dired
buffer and try again.
When OTHER-WINDOW is non-nil, jump to Dired buffer in other window.
When FILE-NAME is non-nil, jump to its line in Dired.
Interactively with prefix argument, read FILE-NAME.

(fn &optional OTHER-WINDOW FILE-NAME)
** SPC o A
:PROPERTIES:
:CUSTOM_ID: 097c5064-d98a-4402-9e02-4328014d4f9e
:END:
*** Function
*org-agenda*
*** Documentation
Dispatch agenda commands to collect entries to the agenda buffer.
Prompts for a command to execute.  Any prefix arg will be passed
on to the selected command.  The default selections are:

a     Call ‘org-agenda-list’ to display the agenda for current day or week.
t     Call ‘org-todo-list’ to display the global todo list.
T     Call ‘org-todo-list’ to display the global todo list, select only
      entries with a specific TODO keyword (the user gets a prompt).
m     Call ‘org-tags-view’ to display headlines with tags matching
      a condition  (the user is prompted for the condition).
M     Like ‘m’, but select only TODO entries, no ordinary headlines.
e     Export views to associated files.
s     Search entries for keywords.
S     Search entries for keywords, only with TODO keywords.
/     Multi occur across all agenda files and also files listed
      in ‘org-agenda-text-search-extra-files’.
<     Restrict agenda commands to buffer, subtree, or region.
      Press several times to get the desired effect.
>     Remove a previous restriction.
#     List "stuck" projects.
!     Configure what "stuck" means.
C     Configure custom agenda commands.

More commands can be added by configuring the variable
‘org-agenda-custom-commands’.  In particular, specific tags and TODO keyword
searches can be pre-defined in this way.

If the current buffer is in Org mode and visiting a file, you can also
first press ‘<’ once to indicate that the agenda should be temporarily
(until the next use of ‘SPC o A’) restricted to the current file.
Pressing ‘<’ twice means to restrict to the current subtree or region
(if active).
** SPC o P
:PROPERTIES:
:CUSTOM_ID: f2ca4317-57a8-4481-aaf6-53be7cf88e53
:END:
*** Function
*+treemacs/find-file*
*** Documentation
Open treemacs (if necessary) and find current file.
** SPC o R
:PROPERTIES:
:CUSTOM_ID: c3ed250b-7275-449b-b46a-2f9fe9736f31
:END:
*** Function
*+eval/open-repl-same-window*
*** Documentation
Opens (or reopens) the REPL associated with the current major-mode and place
the cursor at the prompt.

If ARG (universal argument), prompt for a specific REPL to open.

(fn &optional ARG)
** SPC o b
:PROPERTIES:
:CUSTOM_ID: c42d56df-1cd5-4aaa-bc93-4393b9ed1f94
:END:
*** Function
*browse-url-of-file*
*** Documentation
Ask a WWW browser to display FILE.
Display the current buffer’s file if FILE is nil or if called
interactively.  Turn the filename into a URL with function
‘browse-url-file-url’.  Pass the URL to a browser using the
‘browse-url’ function then run ‘browse-url-of-file-hook’.
** SPC o i
:PROPERTIES:
:CUSTOM_ID: d1b28c1a-f878-4271-b6eb-3d16abf595fb
:END:
*** Function
*imenu-list-smart-toggle*
*** Documentation
Enable or disable ‘imenu-list-minor-mode’ according to buffer’s visibility.
If the imenu-list buffer is displayed in any window, disable
‘imenu-list-minor-mode’, otherwise enable it.
Note that all the windows in every frame searched, even invisible ones, not
only those in the selected frame.

(fn)
** SPC o p
:PROPERTIES:
:CUSTOM_ID: c1b8aaee-e425-4f5c-9a73-3321ecc0eff2
:END:
*** Function
*+treemacs/toggle*
*** Documentation
Initialize or toggle treemacs.

Ensures that only the current project is present and all other projects have
been removed.

Use ‘treemacs’ command for old functionality.
** SPC o r
:PROPERTIES:
:CUSTOM_ID: 60d23955-d838-4d50-94d7-77e1a60448f6
:END:
*** Function
*+eval/open-repl-other-window*
*** Documentation
Does ‘+eval/open-repl’, but in a popup window.

If ARG (universal argument), prompt for a specific REPL to open.

(fn &optional ARG)
** SPC n N
:PROPERTIES:
:CUSTOM_ID: 5b2fe451-598f-4739-8f6f-3027f9ddbbad
:END:
*** Function
*+default/browse-notes*
*** Documentation

** SPC n l
:PROPERTIES:
:CUSTOM_ID: 318398e5-b23b-440a-8e32-f84b010f3faf
:END:
*** Function
*org-store-link*
*** Documentation
Store a link to the current location.

This link is added to ‘org-stored-links’ and can later be inserted
into an Org buffer with ‘org-insert-link’ (‘C-c C-l’).

For some link types, a ‘M-x universal-argument’ prefix ARG is interpreted.  A single
‘M-x universal-argument’ negates ‘org-context-in-file-links’ for file links or
‘org-gnus-prefer-web-links’ for links to Usenet articles.

A ‘M-x universal-argument M-x universal-argument’ prefix ARG forces skipping storing functions that are not
part of Org core.

A ‘M-x universal-argument M-x universal-argument M-x universal-argument’ prefix ARG forces storing a link for each line in the
active region.

Assume the function is called interactively if INTERACTIVE? is
non-nil.

(fn ARG &optional INTERACTIVE\?)
** SPC n n
:PROPERTIES:
:CUSTOM_ID: 4377760d-a48e-437a-ab3f-a60e293b2926
:END:
*** Function
*+default/find-in-notes*
*** Documentation

** SPC n s
:PROPERTIES:
:CUSTOM_ID: b4023007-9482-426c-8a2e-f2261e36d39a
:END:
*** Function
*doom/open-scratch-buffer*
*** Documentation
Opens a scratch pad window in the same major-mode.

If ARG (universal argument), then open a persistent scratch pad buffer. You’ll
be prompted for its name, or to open a previously created. These are stored in
‘doom-scratch-files-dir’.

If a region is active, copy its contents to the scratch pad.
** SPC n x
:PROPERTIES:
:CUSTOM_ID: 9e2f7a7e-0456-4b0e-b853-e19620ab8b25
:END:
*** Function
*org-capture*
*** Documentation
Capture something.

This will let you select a template from ‘org-capture-templates’, and
then file the newly captured information.  The text is immediately
inserted at the target location, and an indirect buffer is shown where
you can edit it.  Pressing ‘C-c C-c’ brings you back to the previous
state of Emacs, so that you can continue your work.

When called interactively with a ‘M-x universal-argument’ prefix argument GOTO, don’t
capture anything, just go to the file/headline where the selected
template stores its notes.

With a ‘M-x universal-argument M-x universal-argument’ prefix argument, go to the last note stored.

When called with a ‘C-0’ (zero) prefix, insert a template at point.

When called with a ‘C-1’ (one) prefix, force prompting for a date when
a datetree entry is made.

ELisp programs can set KEYS to a string associated with a template
in ‘org-capture-templates’.  In this case, interactive selection
will be bypassed.

If ‘org-capture-use-agenda-date’ is non-nil, capturing from the
agenda will use the date at point as the default date.  Then, a
‘C-1’ prefix will tell the capture process to use the HH:MM time
of the day at point (if any) or the current HH:MM time.

(fn &optional GOTO KEYS)
** SPC i s
:PROPERTIES:
:CUSTOM_ID: 167a000a-6b35-4011-8b90-993a3fb10742
:END:
*** Function
*yas-insert-snippet*
*** Documentation
Choose a snippet to expand, pop-up a list of choices according
to ‘yas-prompt-functions’.

With prefix argument NO-CONDITION, bypass filtering of snippets
by condition.
** SPC i y
:PROPERTIES:
:CUSTOM_ID: 80846462-575f-4adc-b4c6-f563337a9c47
:END:
*** Function
*+default/yank-pop*
*** Documentation
Interactively select what text to insert from the kill ring.
** SPC g '
:PROPERTIES:
:CUSTOM_ID: 6447d2ac-f678-4d5e-80ac-ef5c1c420634
:END:
*** Function
*forge-dispatch*
*** Documentation
Dispatch a forge command.
** SPC g /
:PROPERTIES:
:CUSTOM_ID: 6f45bf0d-db98-495e-aaf3-26a44bce0597
:END:
*** Function
*magit-dispatch*
*** Documentation
Invoke a Magit command from a list of available commands.
** SPC g B
:PROPERTIES:
:CUSTOM_ID: 377b1f0b-1c85-4e1d-ba8a-c9b07f9216dd
:END:
*** Function
*magit-blame-addition*
*** Documentation
For each line show the revision in which it was added.
** SPC g C
:PROPERTIES:
:CUSTOM_ID: 87afe0af-944b-44b4-849d-57648d9f14d8
:END:
*** Function
*+magit/clone*
*** Documentation
Like ‘magit-clone’, but supports additional formats on top of absolute URLs:

+ USER/REPO: assumes {‘+magit-default-clone-url’}/USER/REPO
+ REPO: assumes {‘+magit-default-clone-url’}/{USER}/REPO, where {USER} is
  ascertained from your global gitconfig.
** SPC g F
:PROPERTIES:
:CUSTOM_ID: 06a048fd-2d5b-4871-8bb7-8e428684d131
:END:
*** Function
*magit-fetch*
*** Documentation
Fetch from another repository.
** SPC g L
:PROPERTIES:
:CUSTOM_ID: 80de298e-bec2-4877-b78a-aab7b7fa1698
:END:
*** Function
*magit-log*
*** Documentation
Show a commit or reference log.
** SPC g R
:PROPERTIES:
:CUSTOM_ID: 20950724-b6d1-4143-9c9d-d7eb9a535b64
:END:
*** Function
*vc-revert*
*** Documentation
Revert working copies of the selected fileset to their repository contents.
This asks for confirmation if the buffer contents are not identical
to the working revision (except for keyword expansion).

(fn)
** SPC g S
:PROPERTIES:
:CUSTOM_ID: cab158d6-a07a-447f-a7f3-7c3b903bf94d
:END:
*** Function
*magit-stage-file*
*** Documentation
:after advice: ‘+version-control|update-git-gutter’

Stage all changes to FILE.
With a prefix argument or when there is no file at point ask for
the file to be staged.  Otherwise stage the file at point without
requiring confirmation.

(fn FILE)
** SPC g U
:PROPERTIES:
:CUSTOM_ID: 492ddbd7-269c-4dbf-9209-0875e5dc9aa2
:END:
*** Function
*magit-unstage-file*
*** Documentation
:after advice: ‘+version-control|update-git-gutter’

Unstage all changes to FILE.
With a prefix argument or when there is no file at point ask for
the file to be unstaged.  Otherwise unstage the file at point
without requiring confirmation.

(fn FILE)
** SPC g [
:PROPERTIES:
:CUSTOM_ID: 2e9e00d3-ffb1-43b6-b820-b68de20565ef
:END:
*** Function
*git-gutter:previous-hunk*
*** Documentation
Move to previous diff hunk

(fn ARG)
** SPC g ]
:PROPERTIES:
:CUSTOM_ID: 078333bc-daed-46e2-bec8-546f48f572ee
:END:
*** Function
*git-gutter:next-hunk*
*** Documentation
Move to next diff hunk

(fn ARG)
** SPC g g
:PROPERTIES:
:CUSTOM_ID: be633158-9952-4c3e-9c11-3c0915a99e99
:END:
*** Function
*magit-status*
*** Documentation
Show the status of the current Git repository in a buffer.

If the current directory isn’t located within a Git repository,
then prompt for an existing repository or an arbitrary directory,
depending on option ‘magit-repository-directories’, and show the
status of the selected repository instead.

 If that option specifies any existing repositories, then offer
  those for completion and show the status buffer for the
  selected one.

 Otherwise read an arbitrary directory using regular file-name
  completion.  If the selected directory is the top-level of an
  existing working tree, then show the status buffer for that.

 Otherwise offer to initialize the selected directory as a new
  repository.  After creating the repository show its status
  buffer.

These fallback behaviors can also be forced using one or more
prefix arguments:

 With two prefix arguments (or more precisely a numeric prefix
  value of 16 or greater) read an arbitrary directory and act on
  it as described above.  The same could be accomplished using
  the command ‘magit-init’.

 With a single prefix argument read an existing repository, or
  if none can be found based on ‘magit-repository-directories’,
  then fall back to the same behavior as with two prefix
  arguments.

(fn &optional DIRECTORY CACHE)
** SPC g r
:PROPERTIES:
:CUSTOM_ID: 0e371fe0-8c93-4596-aae2-023e21069724
:END:
*** Function
*git-gutter:revert-hunk*
*** Documentation
Revert current hunk.
** SPC g s
:PROPERTIES:
:CUSTOM_ID: a03374e4-b9d7-4aa7-a006-6fd9a77ffc70
:END:
*** Function
*git-gutter:stage-hunk*
*** Documentation
Stage this hunk like ’git add -p’.
** SPC g t
:PROPERTIES:
:CUSTOM_ID: ebf87a91-7c8f-4b7c-a26e-eb5c86eb95dc
:END:
*** Function
*git-timemachine-toggle*
*** Documentation
Toggle git timemachine mode.

(fn)
** SPC g x
:PROPERTIES:
:CUSTOM_ID: 0f58bd0b-d0b4-49eb-b107-34902a0f7932
:END:
*** Function
*magit-file-delete*
*** Documentation
Delete the selected FILES or one file read in the minibuffer.

With a prefix argument FORCE do so even when the files have
uncommitted changes.  When the files aren’t being tracked in
Git, then fallback to using ‘delete-file’.

(fn FILES &optional FORCE)
** SPC f .
:PROPERTIES:
:CUSTOM_ID: 0bd9a0f1-550e-4eac-98f9-179c5e67d024
:END:
*** Function
*counsel-file-jump*
*** Documentation
Jump to a file below the current directory.
List all files within the current directory or any of its subdirectories.
INITIAL-INPUT can be given as the initial minibuffer input.
INITIAL-DIRECTORY, if non-nil, is used as the root directory for search.

(fn &optional INITIAL-INPUT INITIAL-DIRECTORY)
** SPC f /
:PROPERTIES:
:CUSTOM_ID: f23a7abe-065b-49c9-a5a7-5cd4e8f65cc6
:END:
*** Function
*projectile-find-file*
*** Documentation
Jump to a project’s file using completion.
With a prefix arg INVALIDATE-CACHE invalidates the cache first.

(fn &optional INVALIDATE-CACHE)
** SPC f >
:PROPERTIES:
:CUSTOM_ID: 6a963989-407e-47be-991c-b6afeea51272
:END:
*** Function
*doom/browse-in-other-project*
*** Documentation
Preforms ‘find-file’ in a known project of your choosing.
** SPC f ?
:PROPERTIES:
:CUSTOM_ID: bdba04d7-0cbb-42ec-a096-6550940351d6
:END:
*** Function
*doom/find-file-in-other-project*
*** Documentation
Preforms ‘projectile-find-file’ in a known project of your choosing.
** SPC f E
:PROPERTIES:
:CUSTOM_ID: 4fa53e94-1db1-4731-9b4e-a89d794c450e
:END:
*** Function
*+default/browse-emacsd*
*** Documentation

** SPC f P
:PROPERTIES:
:CUSTOM_ID: c4451e27-8e04-4d00-84a1-db425b616e4f
:END:
*** Function
*doom/open-private-config*
*** Documentation
TODO

(fn)
** SPC f R
:PROPERTIES:
:CUSTOM_ID: 3626d691-a3ee-445a-a50f-d93adfaf6f01
:END:
*** Function
*projectile-recentf*
*** Documentation
Show a list of recently visited files in a project.
** SPC f S
:PROPERTIES:
:CUSTOM_ID: cfe21cbd-4efc-4226-8be4-7277a462b5cb
:END:
*** Function
*doom/sudo-find-file*
*** Documentation
Open FILE as root.

(fn FILE)
** SPC f X
:PROPERTIES:
:CUSTOM_ID: 04a5ae29-a371-48fc-a7bb-184256008ef6
:END:
*** Function
*doom/delete-this-file*
*** Documentation
Delete FILENAME (defaults to the file associated with current buffer) and
kills the buffer. If FORCE-P, force the deletion (don’t ask for confirmation).

(fn &optional PATH FORCE-P)
** SPC f a
:PROPERTIES:
:CUSTOM_ID: 6419c48c-ad36-4493-8701-8ec2a35c7162
:END:
*** Function
*projectile-find-other-file*
*** Documentation
Switch between files with the same name but different extensions.
With FLEX-MATCHING, match any file that contains the base name of current file.
Other file extensions can be customized with the variable ‘projectile-other-file-alist’.

(fn &optional FLEX-MATCHING)
** SPC f d
:PROPERTIES:
:CUSTOM_ID: 75cdd776-f4e5-4a10-9d6f-5252b97ce1ab
:END:
*** Function
*dired*
*** Documentation
"Edit" directory DIRNAME--delete, rename, print, etc. some files in it.
Optional second argument SWITCHES specifies the ‘ls’ options used.
(Interactively, use a prefix argument to be able to specify SWITCHES.)

If DIRNAME is a string, Dired displays a list of files in DIRNAME (which
may also have shell wildcards appended to select certain files).

If DIRNAME is a cons, its first element is taken as the directory name
and the rest as an explicit list of files to make directory entries for.
In this case, SWITCHES are applied to each of the files separately, and
therefore switches that control the order of the files in the produced
listing have no effect.

You can flag files for deletion with d and then
delete them by typing x.
Type h after entering Dired for more info.

If DIRNAME is already in a Dired buffer, that buffer is used without refresh.

(fn DIRNAME &optional SWITCHES)
** SPC f e
:PROPERTIES:
:CUSTOM_ID: 7c44ae79-82ff-425e-9646-3b6e8f3ccbf7
:END:
*** Function
*+default/find-in-emacsd*
*** Documentation

** SPC f f
:PROPERTIES:
:CUSTOM_ID: 5d5b3a2c-c39c-49cb-bb48-cad996dabd08
:END:
*** Function
*find-file*
*** Documentation
Edit file FILENAME.
Switch to a buffer visiting file FILENAME,
creating one if none already exists.
Interactively, the default if you just type RET is the current directory,
but the visited file name is available through the minibuffer history:
type M-x next-history-element to pull it into the minibuffer.

The first time M-x next-history-element is used after Emacs prompts for
the file name, the result is affected by ‘file-name-at-point-functions’,
which by default try to guess the file name by looking at point in the
current buffer.  Customize the value of ‘file-name-at-point-functions’
or set it to nil, if you want only the visited file name and the
current directory to be available on first M-x next-history-element
request.

You can visit files on remote machines by specifying something
like /ssh:SOME_REMOTE_MACHINE:FILE for the file name.  You can
also visit local files as a different user by specifying
/sudo::FILE for the file name.
See the Info node ‘(tramp)File name Syntax’ in the Tramp Info
manual, for more about this.

Interactively, or if WILDCARDS is non-nil in a call from Lisp,
expand wildcards (if any) and visit multiple files.  You can
suppress wildcard expansion by setting ‘find-file-wildcards’ to nil.

To visit a file without any kind of conversion and without
automatically choosing a major mode, use M-x find-file-literally.

(fn FILENAME &optional WILDCARDS)
** SPC f p
:PROPERTIES:
:CUSTOM_ID: 38bb4388-3d65-4116-95fd-c63ffc58eea9
:END:
*** Function
*doom/find-file-in-private-config*
*** Documentation
TODO

(fn)
** SPC f r
:PROPERTIES:
:CUSTOM_ID: c76562db-cd7f-475e-9e01-0eed9d61cb46
:END:
*** Function
*recentf-open-files*
*** Documentation
Show a dialog to open a recent file.
If optional argument FILES is non-nil, it is a list of recently-opened
files to choose from.  It defaults to the whole recent list.
If optional argument BUFFER-NAME is non-nil, it is a buffer name to
use for the dialog.  It defaults to "*‘recentf-menu-title’*".
** SPC f s
:PROPERTIES:
:CUSTOM_ID: 6fa9b87e-7273-4e35-a6a9-0de4d9fd56c3
:END:
*** Function
*save-buffer*
*** Documentation
Save current buffer in visited file if modified.
Variations are described below.

By default, makes the previous version into a backup file
 if previously requested or if this is the first save.
Prefixed with one SPC u, marks this version
 to become a backup when the next save is done.
Prefixed with two SPC u’s,
 makes the previous version into a backup file.
Prefixed with three SPC u’s, marks this version
 to become a backup when the next save is done,
 and makes the previous version into a backup file.

With a numeric prefix argument of 0, never make the previous version
into a backup file.

Note that the various variables that control backups, such
as ‘version-control’, ‘backup-enable-predicate’, ‘vc-make-backup-files’,
and ‘backup-inhibited’, to name just the more popular ones, still
control whether a backup will actually be produced, even when you
invoke this command prefixed with two or three SPC u’s.

If a file’s name is FOO, the names of its numbered backup versions are
 FOO.~i~ for various integers i.  A non-numbered backup file is called FOO~.
Numeric backups (rather than FOO~) will be made if value of
 ‘version-control’ is not the atom ‘never’ and either there are already
 numeric versions of the file being backed up, or ‘version-control’ is
 non-nil.
We don’t want excessive versions piling up, so there are variables
 ‘kept-old-versions’, which tells Emacs how many oldest versions to keep,
 and ‘kept-new-versions’, which tells how many newest versions to keep.
 Defaults are 2 old versions and 2 new.
‘dired-kept-versions’ controls dired’s clean-directory (.) command.
If ‘delete-old-versions’ is nil, system will query user
 before trimming versions.  Otherwise it does it silently.

If ‘vc-make-backup-files’ is nil, which is the default,
 no backup files are made for files managed by version control.
 (This is because the version control system itself records previous versions.)

See the subroutine ‘basic-save-buffer’ for more information.

(fn &optional ARG)
** SPC f y
:PROPERTIES:
:CUSTOM_ID: 441e0cdb-7ce9-471c-8411-447af37b90ff
:END:
*** Function
*+default/yank-buffer-filename*
*** Documentation
Copy the current buffer’s path to the kill ring.
** SPC c D
:PROPERTIES:
:CUSTOM_ID: 329cef26-e505-43a0-9d31-0a9362418419
:END:
*** Function
*+lookup/references*
*** Documentation
Show a list of usages of IDENTIFIER (defaults to the symbol at point)

Tries each function in ‘+lookup-references-functions’ until one changes the
point and/or current buffer. Falls back to a naive ripgrep/the_silver_searcher
search otherwise.
** SPC c E
:PROPERTIES:
:CUSTOM_ID: 0b1547c3-b51b-49a7-b0e1-d5abd7b131d7
:END:
*** Function
*+eval:replace-region*
*** Documentation

** SPC c W
:PROPERTIES:
:CUSTOM_ID: 0e356afa-02ab-442c-8ac4-f77a3ad03f3d
:END:
*** Function
*doom/delete-trailing-newlines*
*** Documentation
Trim trailing newlines.

Respects ‘require-final-newline’.
** SPC c c
:PROPERTIES:
:CUSTOM_ID: 277e3f79-00c7-4255-ac55-c3b770bab810
:END:
*** Function
*projectile-compile-project*
*** Documentation
Run project compilation command.

Normally you’ll be prompted for a compilation command, unless
variable ‘compilation-read-command’.  You can force the prompt
with a prefix ARG.

(fn ARG)
** SPC c d
:PROPERTIES:
:CUSTOM_ID: d4268002-10f5-40c7-ab2c-58cbae78c974
:END:
*** Function
*+lookup/definition*
*** Documentation
Jump to the definition of IDENTIFIER (defaults to the symbol at point).

If OTHER-WINDOW (universal argument), open the result in another window.

Each function in ‘+lookup-definition-functions’ is tried until one changes the
point or current buffer. Falls back to dumb-jump, naive
ripgrep/the_silver_searcher text search, then ‘evil-goto-definition’ if
evil-mode is active.
** SPC c e
:PROPERTIES:
:CUSTOM_ID: 6f7dd680-12ba-44b4-87c9-c7e8054f5850
:END:
*** Function
*+eval/buffer-or-region*
*** Documentation
Evaluate the whole buffer.
** SPC c r
:PROPERTIES:
:CUSTOM_ID: 07a72872-94ed-4ad6-9ddf-572e8177e0bd
:END:
*** Function
*+eval/open-repl-other-window*
*** Documentation
Does ‘+eval/open-repl’, but in a popup window.

If ARG (universal argument), prompt for a specific REPL to open.

(fn &optional ARG)
** SPC c w
:PROPERTIES:
:CUSTOM_ID: 2ff4d4df-7cc0-430c-928c-675e646edc7d
:END:
*** Function
*delete-trailing-whitespace*
*** Documentation
Delete trailing whitespace between START and END.
If called interactively, START and END are the start/end of the
region if the mark is active, or of the buffer’s accessible
portion if the mark is inactive.

This command deletes whitespace characters after the last
non-whitespace character in each line between START and END.  It
does not consider formfeed characters to be whitespace.

If this command acts on the entire buffer (i.e. if called
interactively with the mark inactive, or called from Lisp with
END nil), it also deletes all trailing lines at the end of the
buffer if the variable ‘delete-trailing-lines’ is non-nil.

(fn &optional START END)
** SPC c x
:PROPERTIES:
:CUSTOM_ID: af582e8f-e43a-4a37-809b-8510d74afb05
:END:
*** Function
*flycheck-list-errors*
*** Documentation
Show the error list for the current buffer.
** SPC b -
:PROPERTIES:
:CUSTOM_ID: 28a6d99e-0812-4332-8745-af9dbd1dc37f
:END:
*** Function
*doom/clone-and-narrow-buffer*
*** Documentation
Restrict editing in this buffer to the current region, indirectly. With CLONE-P,
clone the buffer and hard-narrow the selection. If mark isn’t active, then widen
the buffer (if narrowed).

Inspired from http://demonastery.org/2013/04/emacs-evil-narrow-region/
** SPC b B
:PROPERTIES:
:CUSTOM_ID: d68f0498-9d90-4b97-87e8-1ad5baadc464
:END:
*** Function
*switch-to-buffer*
*** Documentation
:around advice: ‘ad-Advice-switch-to-buffer’
:around advice: ‘doom*run-switch-buffer-hooks’

Display buffer BUFFER-OR-NAME in the selected window.

WARNING: This is NOT the way to work on another buffer temporarily
within a Lisp program!  Use ‘set-buffer’ instead.  That avoids
messing with the window-buffer correspondences.

If the selected window cannot display the specified buffer
because it is a minibuffer window or strongly dedicated to
another buffer, call ‘pop-to-buffer’ to select the buffer in
another window.  In interactive use, if the selected window is
strongly dedicated to its buffer, the value of the option
‘switch-to-buffer-in-dedicated-window’ specifies how to proceed.

If called interactively, read the buffer name using ‘read-buffer’.
The variable ‘confirm-nonexistent-file-or-buffer’ determines
whether to request confirmation before creating a new buffer.
See ‘read-buffer’ for features related to input and completion
of buffer names.

BUFFER-OR-NAME may be a buffer, a string (a buffer name), or nil.
If BUFFER-OR-NAME is a string that does not identify an existing
buffer, create a buffer with that name.  If BUFFER-OR-NAME is
nil, switch to the buffer returned by ‘other-buffer’.

If optional argument NORECORD is non-nil, do not put the buffer
at the front of the buffer list, and do not make the window
displaying it the most recently selected one.

If optional argument FORCE-SAME-WINDOW is non-nil, the buffer
must be displayed in the selected window when called
non-interactively; if that is impossible, signal an error rather
than calling ‘pop-to-buffer’.  It has no effect when the option
‘switch-to-buffer-obey-display-actions’ is non-nil.

The option ‘switch-to-buffer-preserve-window-point’ can be used
to make the buffer appear at its last position in the selected
window.

If the option ‘switch-to-buffer-obey-display-actions’ is non-nil,
run the function ‘pop-to-buffer-same-window’ instead.
This may display the buffer in another window as specified by
‘display-buffer-overriding-action’, ‘display-buffer-alist’ and
other display related variables.  If this results in displaying
the buffer in the selected window, window start and point are adjusted
as prescribed by the option ‘switch-to-buffer-preserve-window-point’.
Otherwise, these are left alone.

Return the buffer switched to.

(fn BUFFER-OR-NAME &optional NORECORD FORCE-SAME-WINDOW)
** SPC b N
:PROPERTIES:
:CUSTOM_ID: 68fad855-9f08-4968-b4e8-8ade54aae707
:END:
*** Function
*evil-buffer-new*
*** Documentation
Creates a new buffer replacing the current window, optionally
   editing a certain FILE
** SPC b S
:PROPERTIES:
:CUSTOM_ID: f0e6c89e-63f3-41a5-9133-384256d5db13
:END:
*** Function
*doom/sudo-this-file*
*** Documentation
Open the current file as root.

(fn)
** SPC b [
:PROPERTIES:
:CUSTOM_ID: 023ee488-f3ba-433d-868a-05d27aec24cc
:END:
*** Function
*previous-buffer*
*** Documentation
In selected window switch to previous buffer.
** SPC b ]
:PROPERTIES:
:CUSTOM_ID: f5b38e30-260e-43f7-be4c-d4c13a8d0ede
:END:
*** Function
*next-buffer*
*** Documentation
In selected window switch to next buffer.
** SPC b b
:PROPERTIES:
:CUSTOM_ID: 319f4d01-a04e-4d89-a13c-361e8b65468a
:END:
*** Function
*persp-switch-to-buffer*
*** Documentation
Switch to buffer, read buffer with restriction to current perspective.
** SPC b k
:PROPERTIES:
:CUSTOM_ID: 41f8111a-a787-4f38-af71-0e9f408fd147
:END:
*** Function
*kill-this-buffer*
*** Documentation
:around advice: ‘doom*switch-to-fallback-buffer-maybe’

Kill the current buffer.
When called in the minibuffer, get out of the minibuffer
using ‘abort-recursive-edit’.

This command can be reliably invoked only from the menu bar,
otherwise it could decide to silently do nothing.

(fn)
** SPC b n
:PROPERTIES:
:CUSTOM_ID: 007139e3-8613-4a6e-9f49-6049f783ffc0
:END:
*** Function
*next-buffer*
*** Documentation
In selected window switch to next buffer.
** SPC b o
:PROPERTIES:
:CUSTOM_ID: 4a1355ad-d96a-40a3-a3e5-2c5769cafe01
:END:
*** Function
*doom/kill-other-buffers*
*** Documentation
Kill all other buffers (besides the current one).

If PROJECT-P (universal argument), kill only buffers that belong to the current
project.
** SPC b p
:PROPERTIES:
:CUSTOM_ID: 24f4e616-c3c6-4266-88b8-404c61dbc4aa
:END:
*** Function
*previous-buffer*
*** Documentation
In selected window switch to previous buffer.
** SPC b s
:PROPERTIES:
:CUSTOM_ID: 2a015be2-eb68-4fd4-ba8a-d4d8df158744
:END:
*** Function
*save-buffer*
*** Documentation
Save current buffer in visited file if modified.
Variations are described below.

By default, makes the previous version into a backup file
 if previously requested or if this is the first save.
Prefixed with one SPC u, marks this version
 to become a backup when the next save is done.
Prefixed with two SPC u’s,
 makes the previous version into a backup file.
Prefixed with three SPC u’s, marks this version
 to become a backup when the next save is done,
 and makes the previous version into a backup file.

With a numeric prefix argument of 0, never make the previous version
into a backup file.

Note that the various variables that control backups, such
as ‘version-control’, ‘backup-enable-predicate’, ‘vc-make-backup-files’,
and ‘backup-inhibited’, to name just the more popular ones, still
control whether a backup will actually be produced, even when you
invoke this command prefixed with two or three SPC u’s.

If a file’s name is FOO, the names of its numbered backup versions are
 FOO.~i~ for various integers i.  A non-numbered backup file is called FOO~.
Numeric backups (rather than FOO~) will be made if value of
 ‘version-control’ is not the atom ‘never’ and either there are already
 numeric versions of the file being backed up, or ‘version-control’ is
 non-nil.
We don’t want excessive versions piling up, so there are variables
 ‘kept-old-versions’, which tells Emacs how many oldest versions to keep,
 and ‘kept-new-versions’, which tells how many newest versions to keep.
 Defaults are 2 old versions and 2 new.
‘dired-kept-versions’ controls dired’s clean-directory (.) command.
If ‘delete-old-versions’ is nil, system will query user
 before trimming versions.  Otherwise it does it silently.

If ‘vc-make-backup-files’ is nil, which is the default,
 no backup files are made for files managed by version control.
 (This is because the version control system itself records previous versions.)

See the subroutine ‘basic-save-buffer’ for more information.

(fn &optional ARG)
** SPC b x
:PROPERTIES:
:CUSTOM_ID: 5b5d44ab-77db-4c39-b0a1-6006acca30a9
:END:
*** Function
*doom/open-scratch-buffer*
*** Documentation
Opens a scratch pad window in the same major-mode.

If ARG (universal argument), then open a persistent scratch pad buffer. You’ll
be prompted for its name, or to open a previously created. These are stored in
‘doom-scratch-files-dir’.

If a region is active, copy its contents to the scratch pad.
** SPC b z
:PROPERTIES:
:CUSTOM_ID: 911f8f07-dede-4c86-923c-208c6c6e18d5
:END:
*** Function
*bury-buffer*
*** Documentation
Put BUFFER-OR-NAME at the end of the list of all buffers.
There it is the least likely candidate for ‘other-buffer’ to
return; thus, the least likely buffer for SPC < to
select by default.

You can specify a buffer name as BUFFER-OR-NAME, or an actual
buffer object.  If BUFFER-OR-NAME is nil or omitted, bury the
current buffer.  Also, if BUFFER-OR-NAME is nil or omitted,
remove the current buffer from the selected window if it is
displayed there.

(fn &optional BUFFER-OR-NAME)
** SPC TAB TAB
:PROPERTIES:
:CUSTOM_ID: 9c3ba37e-2aa1-4408-83ed-9089f39d40b5
:END:
*** Function
*+workspace/display*
*** Documentation
Display a list of workspaces (like tabs) in the echo area.
** SPC TAB .
:PROPERTIES:
:CUSTOM_ID: 5019af10-619a-4507-a3af-0702eb4c0600
:END:
*** Function
*+workspace/switch-to*
*** Documentation
Switch to a workspace at a given INDEX. A negative number will start from the
end of the workspace list.
** SPC TAB 0
:PROPERTIES:
:CUSTOM_ID: 1d03d4d8-bd19-4736-9626-cd3579aa4a68
:END:
*** Function
*+workspace/switch-to-last*
*** Documentation
Switch to the last workspace.
** SPC TAB R
:PROPERTIES:
:CUSTOM_ID: 14096506-e779-4166-8702-9f2e79f19a3e
:END:
*** Function
*+workspace/restore-last-session*
*** Documentation
TODO

(fn)
** SPC TAB [
:PROPERTIES:
:CUSTOM_ID: ad502bba-1099-4c4a-afec-7087d6f04137
:END:
*** Function
*+workspace/switch-left*
*** Documentation

** SPC TAB ]
:PROPERTIES:
:CUSTOM_ID: beb80fa5-ca53-4ee3-9eb1-a1588c5430f8
:END:
*** Function
*+workspace/switch-right*
*** Documentation

** SPC TAB d
:PROPERTIES:
:CUSTOM_ID: fcd7879a-0a00-4448-a508-8f0ed3249a5e
:END:
*** Function
*+workspace/delete*
*** Documentation
Delete this workspace. If called with C-u, prompts you for the name of the
workspace to delete.
** SPC TAB l
:PROPERTIES:
:CUSTOM_ID: 4057c04d-8f84-4e26-833d-0fa1aa3a9f04
:END:
*** Function
*+workspace/load*
*** Documentation
Load a workspace and switch to it. If called with C-u, try to reload the
current workspace (by name) from session files.
** SPC TAB n
:PROPERTIES:
:CUSTOM_ID: 695472c7-79ff-4266-bb7d-b1485e59d74e
:END:
*** Function
*+workspace/new*
*** Documentation
Create a new workspace named NAME. If CLONE-P is non-nil, clone the current
workspace, otherwise the new workspace is blank.
** SPC TAB r
:PROPERTIES:
:CUSTOM_ID: 941fe096-93f4-469a-afc0-62c495240252
:END:
*** Function
*+workspace/rename*
*** Documentation
Rename the current workspace.
** SPC TAB s
:PROPERTIES:
:CUSTOM_ID: 03cf9a7a-c3b9-45b0-b65c-f2f496fbd2a1
:END:
*** Function
*+workspace/save*
*** Documentation
Save the current workspace. If called with C-u, autosave the current
workspace.
** SPC TAB x
:PROPERTIES:
:CUSTOM_ID: 890c2e11-73ad-476b-943b-80d45620b30d
:END:
*** Function
*+workspace/kill-session*
*** Documentation
Delete the current session, all workspaces, windows and their buffers.
** SPC / I
:PROPERTIES:
:CUSTOM_ID: e7441417-829b-45dd-a34e-a2b23b4df931
:END:
*** Function
*imenu-anywhere*
*** Documentation
Go to imenu tag defined in all reachable buffers.
Reachable buffers are determined by applying functions in
‘imenu-anywhere-buffer-filter-functions’ to all buffers returned
by ‘imenu-anywhere-buffer-list-function’.

Sorting is done within each buffer and takes into account items’
length. Thus more recent buffers in ‘buffer-list’ and shorter
entries have higher priority.

(fn)
** SPC / b
:PROPERTIES:
:CUSTOM_ID: 165c441e-ab52-4517-a695-7b4f27607f6a
:END:
*** Function
*swiper*
*** Documentation
‘isearch’ with an overview.
When non-nil, INITIAL-INPUT is the initial search pattern.

(fn &optional INITIAL-INPUT)
** SPC / d
:PROPERTIES:
:CUSTOM_ID: 324c326d-b46b-41aa-bc49-a9e9f177d8c6
:END:
*** Function
*+default/search-from-cwd*
*** Documentation
Conduct a text search in files under the current folder.
If prefix ARG is set, prompt for a directory to search from.
** SPC / i
:PROPERTIES:
:CUSTOM_ID: 5acde342-4342-4312-b7f7-a44b21b78e76
:END:
*** Function
*imenu*
*** Documentation
Jump to a place in the buffer chosen using a buffer menu or mouse menu.
INDEX-ITEM specifies the position.  See ‘imenu-choose-buffer-index’
for more information.

(fn INDEX-ITEM)
** SPC / l
:PROPERTIES:
:CUSTOM_ID: 57ca7975-ea47-4837-bf4b-89e518b492d2
:END:
*** Function
*ace-link*
*** Documentation
Call the ace link function for the current ‘major-mode’

(fn)
** SPC / o
:PROPERTIES:
:CUSTOM_ID: 7a257daa-ac79-4bb5-9b2c-c02c724ef3a2
:END:
*** Function
*+lookup/online-select*
*** Documentation
Runs ‘+lookup/online’, but always prompts for the provider to use.
** SPC / p
:PROPERTIES:
:CUSTOM_ID: 7858ddc8-826c-4d30-99f7-02c347dca907
:END:
*** Function
*+default/search-project*
*** Documentation
Conduct a text search in files under the project root.
If prefix ARG is set, prompt for a project to search from.
** SPC h C-a
:PROPERTIES:
:CUSTOM_ID: 8bd28223-356f-43cf-9b8c-6122b92c8932
:END:
*** Function
*about-emacs*
*** Documentation
Display the *About GNU Emacs* buffer.
A fancy display is used on graphic displays, normal otherwise.
** SPC h C-c
:PROPERTIES:
:CUSTOM_ID: a759054d-fed2-48b8-99dc-dee8abd658f2
:END:
*** Function
*describe-coding-system*
*** Documentation
Display information about CODING-SYSTEM.

(fn CODING-SYSTEM)
** SPC h C-d
:PROPERTIES:
:CUSTOM_ID: 1222b38b-ca0f-40a8-941c-60057984b52b
:END:
*** Function
*view-emacs-debugging*
*** Documentation
Display info on how to debug Emacs problems.
** SPC h C-e
:PROPERTIES:
:CUSTOM_ID: e7b872d0-441e-43c2-a74e-351ad408a32b
:END:
*** Function
*view-external-packages*
*** Documentation
Display info on where to get more Emacs packages.
** SPC h C-f
:PROPERTIES:
:CUSTOM_ID: a054e492-e31f-4310-a53e-d3eff80a0a7e
:END:
*** Function
*view-emacs-FAQ*
*** Documentation
Display the Emacs Frequently Asked Questions (FAQ) file.
** SPC h C-h
:PROPERTIES:
:CUSTOM_ID: 9295daa6-561a-48d1-8ff4-17753c11b9e3
:END:
*** Function
*help-for-help*
*** Documentation
Help command.
** SPC h C-k
:PROPERTIES:
:CUSTOM_ID: 2d76f838-070b-47ea-a28a-edacf595d841
:END:
*** Function
*describe-key-briefly*
*** Documentation
Print the name of the functions KEY-LIST invokes.
KEY-LIST is a list of pairs (SEQ . RAW-SEQ) of key sequences, where
RAW-SEQ is the untranslated form of the key sequence SEQ.
If INSERT (the prefix arg) is non-nil, insert the message in the buffer.

While reading KEY-LIST interactively, this command temporarily enables
menu items or tool-bar buttons that are disabled to allow getting help
on them.

(fn &optional KEY-LIST INSERT UNTRANSLATED)
** SPC h C-l
:PROPERTIES:
:CUSTOM_ID: 48b97c49-0a89-41c8-af0f-30a1c2cdc02d
:END:
*** Function
*describe-language-environment*
*** Documentation
Describe how Emacs supports language environment LANGUAGE-NAME.

(fn LANGUAGE-NAME)
** SPC h RET
:PROPERTIES:
:CUSTOM_ID: 260569d7-34b8-4ba3-9061-2445b752d90b
:END:
*** Function
*info-emacs-manual*
*** Documentation
Display the Emacs manual in Info mode.
** SPC h C-n
:PROPERTIES:
:CUSTOM_ID: 23d24549-95b8-407a-86b1-6235f2c06ed2
:END:
*** Function
*view-emacs-news*
*** Documentation
Display info on recent changes to Emacs.
With argument, display info only for the selected version.

(fn &optional VERSION)
** SPC h C-o
:PROPERTIES:
:CUSTOM_ID: 93f1eb32-2d90-4822-96fe-d6e5b75840d7
:END:
*** Function
*describe-distribution*
*** Documentation
Display info on how to obtain the latest version of GNU Emacs.
** SPC h C-p
:PROPERTIES:
:CUSTOM_ID: e079a9b1-b3b1-4924-9923-cdaff4047908
:END:
*** Function
*view-emacs-problems*
*** Documentation
Display info on known problems with Emacs and possible workarounds.
** SPC h C-s
:PROPERTIES:
:CUSTOM_ID: d195498e-6e80-413d-8cee-3f890b06cb7e
:END:
*** Function
*search-forward-help-for-help*
*** Documentation
Search forward "help window".
** SPC h C-t
:PROPERTIES:
:CUSTOM_ID: bff59c71-b309-4e15-bb83-75c43e3be1f5
:END:
*** Function
*view-emacs-todo*
*** Documentation
Display the Emacs TODO list.

(fn &optional ARG)
** SPC h C-v
:PROPERTIES:
:CUSTOM_ID: ce608d29-9a41-4a5e-8604-ff46449046c2
:END:
*** Function
*doom/version*
*** Documentation
Display the current version of Doom & Emacs, including the current Doom
branch and commit.
** SPC h C-w
:PROPERTIES:
:CUSTOM_ID: e59eba1c-3b37-4009-96b2-414b16c61a8b
:END:
*** Function
*describe-no-warranty*
*** Documentation
Display info on all the kinds of warranty Emacs does NOT have.
** SPC h C-\
:PROPERTIES:
:CUSTOM_ID: 70a7bf65-2854-4548-b31b-e1103c54876e
:END:
*** Function
*describe-input-method*
*** Documentation
Describe input method INPUT-METHOD.

(fn INPUT-METHOD)
** SPC h '
:PROPERTIES:
:CUSTOM_ID: 5de27659-5aeb-489c-94cf-054ca5d232e8
:END:
*** Function
*describe-char*
*** Documentation
Describe position POS (interactively, point) and the char after POS.
POS is taken to be in BUFFER, or the current buffer if BUFFER is nil.
The information is displayed in buffer ‘*Help*’.

The position information includes POS; the total size of BUFFER; the
region limits, if narrowed; the column number; and the horizontal
scroll amount, if the buffer is horizontally scrolled.

The character information includes:
 its codepoint;
 its charset (see ‘char-charset’), overridden by the ‘charset’ text
   property at POS, if any;
 the codepoint of the character in the above charset;
 the character’s script (as defined by ‘char-script-table’)
 the character’s syntax, as produced by ‘syntax-after’
   and ‘internal-describe-syntax-value’;
 its category (see ‘char-category-set’ and ‘describe-char-categories’);
 how to input the character using the keyboard and input methods;
 how the character is encoded in BUFFER and in BUFFER’s file;
 the font and font glyphs used to display the character;
 the composition information for displaying the character (if relevant);
 the character’s canonical name and other properties defined by the
   Unicode Data Base;
 and widgets, buttons, overlays, and text properties relevant to POS.

(fn POS &optional BUFFER)
** SPC h .
:PROPERTIES:
:CUSTOM_ID: bd0eabce-e5e0-43e4-b020-a2441e62bda2
:END:
*** Function
*display-local-help*
*** Documentation
Display local help in the echo area.
This displays a short help message, namely the string produced by
the ‘kbd-help’ property at point.  If ‘kbd-help’ does not produce
a string, but the ‘help-echo’ property does, then that string is
printed instead.

A numeric argument ARG prevents display of a message in case
there is no help.  While ARG can be used interactively, it is
mainly meant for use from Lisp.

(fn &optional ARG)
** SPC h ?
:PROPERTIES:
:CUSTOM_ID: 371dbf06-f937-44a9-940c-a45ded2d2e7c
:END:
*** Function
*help-for-help*
*** Documentation
Help command.
** SPC h A
:PROPERTIES:
:CUSTOM_ID: 2370416e-7eb8-4587-9042-e9b51a52abbe
:END:
*** Function
*doom/describe-autodefs*
*** Documentation
Open the documentation of Doom autodefs.

What is an autodef? It’s a function or macro that is always defined, even if its
containing module is disabled (in which case it will safely no-op). This
syntactic sugar lets you use them without needing to check if they are
available.

(fn AUTODEF)
** SPC h B
:PROPERTIES:
:CUSTOM_ID: 84e4991a-b693-4526-b154-546fb67457cd
:END:
*** Function
*doom/open-bug-report*
*** Documentation
Open a markdown buffer destinated to populate the New Issue page on Doom
Emacs’ issue tracker.

If called when a backtrace buffer is present, it and the output of ‘doom-info’
will be automatically appended to the result.
** SPC h C
:PROPERTIES:
:CUSTOM_ID: a0810758-274c-421b-bc35-a7300662e14b
:END:
*** Function
*describe-coding-system*
*** Documentation
Display information about CODING-SYSTEM.

(fn CODING-SYSTEM)
** SPC h D
:PROPERTIES:
:CUSTOM_ID: c7542ba0-0002-40b9-818b-53e4dec59778
:END:
*** Function
*doom/open-manual*
*** Documentation
TODO

(fn)
** SPC h E
:PROPERTIES:
:CUSTOM_ID: 779869f2-7f6c-4a16-a562-a6e3df299811
:END:
*** Function
*doom/open-vanilla-sandbox*
*** Documentation
Open the Emacs Lisp sandbox.

This is a test bed for running Emacs Lisp in an instance of Emacs with varying
amounts of Doom loaded, including:

  a) vanilla Emacs (nothing loaded),
  b) vanilla Doom (only Doom core) and
  c) Doom + modules - your private config.

This is done without sacrificing access to installed packages. Use the sandbox
to reproduce bugs and determine if Doom is to blame.
** SPC h F
:PROPERTIES:
:CUSTOM_ID: 30cc556b-c111-4334-9e60-4a8d924242d0
:END:
*** Function
*describe-face*
*** Documentation
Display the properties of face FACE on FRAME.
Interactively, FACE defaults to the faces of the character after point
and FRAME defaults to the selected frame.

If the optional argument FRAME is given, report on face FACE in that frame.
If FRAME is t, report on the defaults for face FACE (for new frames).
If FRAME is omitted or nil, use the selected frame.

(fn FACE &optional FRAME)
** SPC h I
:PROPERTIES:
:CUSTOM_ID: b9e9e349-815b-4d79-9249-30c207a876df
:END:
*** Function
*describe-input-method*
*** Documentation
Describe input method INPUT-METHOD.

(fn INPUT-METHOD)
** SPC h K
:PROPERTIES:
:CUSTOM_ID: 5f89992d-e664-493c-a16e-a2910130f3f4
:END:
*** Function
*Info-goto-emacs-key-command-node*
*** Documentation
Go to the node in the Emacs manual which describes the command bound to KEY.
KEY is a string.
Interactively, if the binding is ‘execute-extended-command’, a command is read.
The command is found by looking up in Emacs manual’s indices
or in another manual found via COMMAND’s ‘info-file’ property or
the variable ‘Info-file-list-for-emacs’.

(fn KEY)
** SPC h L
:PROPERTIES:
:CUSTOM_ID: b666eebf-22a1-4b08-a559-6b4962265e6e
:END:
*** Function
*global-command-log-mode*
*** Documentation

** SPC h M
:PROPERTIES:
:CUSTOM_ID: e020580f-8090-416a-bd42-6e52a71ad1eb
:END:
*** Function
*doom/describe-active-minor-mode*
*** Documentation
Get information on an active minor mode. Use ‘describe-minor-mode’ for a
selection of all minor-modes, active or not.

(fn MODE)
** SPC h O
:PROPERTIES:
:CUSTOM_ID: aba46802-da35-4223-baca-97b822056462
:END:
*** Function
*+lookup/online*
*** Documentation
Looks up SEARCH (a string) in you browser using PROVIDER.

PROVIDER should be a key of ‘+lookup-provider-url-alist’.

When used interactively, it will prompt for a query and, for the first time, the
provider from ‘+lookup-provider-url-alist’. On consecutive uses, the last
provider will be reused. If the universal argument is supplied, always prompt
for the provider.
** SPC h P
:PROPERTIES:
:CUSTOM_ID: e05bdc27-1f3c-4e29-936e-777e1c22af23
:END:
*** Function
*find-library*
*** Documentation
Find the Emacs Lisp source of LIBRARY.

Interactively, prompt for LIBRARY using the one at or near point.

(fn LIBRARY)
** SPC h S
:PROPERTIES:
:CUSTOM_ID: e6b3fad8-a4d5-46ff-ba77-caeff9b35327
:END:
*** Function
*info-lookup-symbol*
*** Documentation
:after advice: ‘+popup*switch-to-info-window’

Display the definition of SYMBOL, as found in the relevant manual.
When this command is called interactively, it reads SYMBOL from the
minibuffer.  In the minibuffer, use M-n to yank the default argument
value into the minibuffer so you can edit it.  The default symbol is the
one found at point.

With prefix arg MODE a query for the symbol help mode is offered.

(fn SYMBOL &optional MODE)
** SPC h T
:PROPERTIES:
:CUSTOM_ID: e5151b05-cb18-4328-a7a9-f183a0c0e3b7
:END:
*** Function
*doom/toggle-profiler*
*** Documentation
Toggle the Emacs profiler. Run it again to see the profiling report.
** SPC h V
:PROPERTIES:
:CUSTOM_ID: 195ae8b3-fd61-4e8f-8a3b-08afc3e3c2e9
:END:
*** Function
*set-variable*
*** Documentation
Set VARIABLE to VALUE.  VALUE is a Lisp object.
VARIABLE should be a user option variable name, a Lisp variable
meant to be customized by users.  You should enter VALUE in Lisp syntax,
so if you want VALUE to be a string, you must surround it with doublequotes.
VALUE is used literally, not evaluated.

If VARIABLE has a ‘variable-interactive’ property, that is used as if
it were the arg to ‘interactive’ (which see) to interactively read VALUE.

If VARIABLE has been defined with ‘defcustom’, then the type information
in the definition is used to check that VALUE is valid.

Note that this function is at heart equivalent to the basic ‘set’ function.
For a variable defined with ‘defcustom’, it does not pay attention to
any :set property that the variable might have (if you want that, use
M-x customize-set-variable instead).

With a prefix argument, set VARIABLE to VALUE buffer-locally.

(fn VARIABLE VALUE &optional MAKE-LOCAL)
** SPC h W
:PROPERTIES:
:CUSTOM_ID: 556e6136-bce5-46aa-a860-e719ef570ddf
:END:
*** Function
*+default/man-or-woman*
*** Documentation
Invoke ‘man’ if man is installed, otherwise use ‘woman’.
** SPC h a
:PROPERTIES:
:CUSTOM_ID: 8f341881-a381-42b8-9090-2dbd958b967f
:END:
*** Function
*apropos*
*** Documentation
Show all meaningful Lisp symbols whose names match PATTERN.
Symbols are shown if they are defined as functions, variables, or
faces, or if they have nonempty property lists.

PATTERN can be a word, a list of words (separated by spaces),
or a regexp (using some regexp special characters).  If it is a word,
search for matches for that word as a substring.  If it is a list of words,
search for matches for any two (or more) of those words.

With SPC u prefix, or if ‘apropos-do-all’ is non-nil,
consider all symbols (if they match PATTERN).

Returns list of symbols and documentation found.

(fn PATTERN &optional DO-ALL)
** SPC h b
:PROPERTIES:
:CUSTOM_ID: f6c6cd82-00bf-4832-9d2d-f5724b3a809b
:END:
*** Function
*describe-bindings*
*** Documentation
Display a buffer showing a list of all defined keys, and their definitions.
The keys are displayed in order of precedence.

The optional argument PREFIX, if non-nil, should be a key sequence;
then we display only bindings that start with that prefix.
The optional argument BUFFER specifies which buffer’s bindings
to display (default, the current buffer).  BUFFER can be a buffer
or a buffer name.

(fn &optional PREFIX BUFFER)
** SPC h c
:PROPERTIES:
:CUSTOM_ID: d8834fbe-cb3f-4725-8760-cc1a60a0a027
:END:
*** Function
*describe-key-briefly*
*** Documentation
Print the name of the functions KEY-LIST invokes.
KEY-LIST is a list of pairs (SEQ . RAW-SEQ) of key sequences, where
RAW-SEQ is the untranslated form of the key sequence SEQ.
If INSERT (the prefix arg) is non-nil, insert the message in the buffer.

While reading KEY-LIST interactively, this command temporarily enables
menu items or tool-bar buttons that are disabled to allow getting help
on them.

(fn &optional KEY-LIST INSERT UNTRANSLATED)
** SPC h d
:PROPERTIES:
:CUSTOM_ID: a1bbf15e-1023-4453-b90a-6fffde357950
:END:
*** Function
*doom/describe-module*
*** Documentation
Open the documentation of CATEGORY MODULE.

CATEGORY is a keyword and MODULE is a symbol. e.g. :feature and ’evil.

Automatically selects a) the module at point (in private init files), b) the
module derived from a ‘featurep!’ or ‘require!’ call, c) the module that the
current file is in, or d) the module associated with the current major mode (see
‘doom--module-mode-alist’).

(fn CATEGORY MODULE)
** SPC h e
:PROPERTIES:
:CUSTOM_ID: 815de66f-6791-49d8-bed9-639a969dccd7
:END:
*** Function
*view-echo-area-messages*
*** Documentation
View the log of recent echo-area messages: the ‘*Messages*’ buffer.
The number of messages retained in that buffer
is specified by the variable ‘message-log-max’.
** SPC h f
:PROPERTIES:
:CUSTOM_ID: ff3bdf04-c0e5-4a64-996b-261a2514dfc7
:END:
*** Function
*describe-function*
*** Documentation
Display the full documentation of FUNCTION (a symbol).
When called from lisp, FUNCTION may also be a function object.

(fn FUNCTION)
** SPC h g
:PROPERTIES:
:CUSTOM_ID: c4a4b76b-2d8e-4f2d-a1b5-43ab554b7a78
:END:
*** Function
*describe-gnu-project*
*** Documentation
Browse online information on the GNU project.
** SPC h h
:PROPERTIES:
:CUSTOM_ID: 045b0a92-3056-4b04-9993-7160f865946d
:END:
*** Function
*doom/describe-symbol*
*** Documentation
Show help for SYMBOL, a variable, function or macro.

(fn SYMBOL)
** SPC h i
:PROPERTIES:
:CUSTOM_ID: 5ed2e118-29e0-45b3-8619-96c0f8fc7643
:END:
*** Function
*info*
*** Documentation
Enter Info, the documentation browser.
Optional argument FILE-OR-NODE specifies the file to examine;
the default is the top-level directory of Info.
Called from a program, FILE-OR-NODE may specify an Info node of the form
"(FILENAME)NODENAME".
Optional argument BUFFER specifies the Info buffer name;
the default buffer name is *info*.  If BUFFER exists,
just switch to BUFFER.  Otherwise, create a new buffer
with the top-level Info directory.

In interactive use, a non-numeric prefix argument directs
this command to read a file name from the minibuffer.

A numeric prefix argument of N selects an Info buffer named "*info*<N>".

The search path for Info files is in the variable ‘Info-directory-list’.
The top-level Info directory is made by combining all the files named ‘dir’
in all the directories in that path.

See a list of available Info commands in ‘Info-mode’.

(fn &optional FILE-OR-NODE BUFFER)
** SPC h k
:PROPERTIES:
:CUSTOM_ID: fdae618f-12bd-4d91-acef-d77ba08861ca
:END:
*** Function
*describe-key*
*** Documentation
Display documentation of the function invoked by KEY-LIST.
KEY-LIST can be any kind of a key sequence; it can include keyboard events,
mouse events, and/or menu events.  When calling from a program,
pass KEY-LIST as a list of elements (SEQ . RAW-SEQ) where SEQ is
a key-sequence and RAW-SEQ is its untranslated form.

While reading KEY-LIST interactively, this command temporarily enables
menu items or tool-bar buttons that are disabled to allow getting help
on them.

BUFFER is the buffer in which to lookup those keys; it defaults to the
current buffer.

(fn &optional KEY-LIST BUFFER UP-EVENT)
** SPC h l
:PROPERTIES:
:CUSTOM_ID: 1f20349f-bc75-43d5-b03b-ff0fd9c7ee29
:END:
*** Function
*view-lossage*
*** Documentation
Display last few input keystrokes and the commands run.
For convenience this uses the same format as
‘edit-last-kbd-macro’.

To record all your input, use ‘open-dribble-file’.
** SPC h m
:PROPERTIES:
:CUSTOM_ID: 2b2f0e9c-f808-4907-adad-8c54601ad61d
:END:
*** Function
*describe-mode*
*** Documentation
Display documentation of current major mode and minor modes.
A brief summary of the minor modes comes first, followed by the
major mode description.  This is followed by detailed
descriptions of the minor modes, each on a separate page.

For this to work correctly for a minor mode, the mode’s indicator
variable (listed in ‘minor-mode-alist’) must also be a function
whose documentation describes the minor mode.

If called from Lisp with a non-nil BUFFER argument, display
documentation for the major and minor modes of that buffer.

(fn &optional BUFFER)
** SPC h n
:PROPERTIES:
:CUSTOM_ID: 04d9248e-407d-4bb5-86ce-82a3a0f9bfeb
:END:
*** Function
*doom/open-news*
*** Documentation
TODO

(fn)
** SPC h o
:PROPERTIES:
:CUSTOM_ID: dd3d9a7c-a09b-4f92-afd7-8f215799ccee
:END:
*** Function
*describe-symbol*
*** Documentation
Display the full documentation of SYMBOL.
Will show the info of SYMBOL as a function, variable, and/or face.
Optional arguments BUFFER and FRAME specify for which buffer and
frame to show the information about SYMBOL; they default to the
current buffer and the selected frame, respectively.

(fn SYMBOL &optional BUFFER FRAME)
** SPC h p
:PROPERTIES:
:CUSTOM_ID: a8ec95ce-a969-44b4-9968-38e946b9aeef
:END:
*** Function
*doom/describe-package*
*** Documentation
Like ‘describe-packages’, but is Doom aware.

Only shows installed packages. Includes information about where packages are
defined and configured.

If prefix arg is prsent, refresh the cache.

(fn PACKAGE)
** SPC h q
:PROPERTIES:
:CUSTOM_ID: 411fe133-4f1f-47d5-8159-932c1da1a3b2
:END:
*** Function
*help-quit*
*** Documentation
Just exit from the Help command’s command loop.
** SPC h s
:PROPERTIES:
:CUSTOM_ID: a5e5a1c1-ec70-43bb-b4ec-85ad07025432
:END:
*** Function
*describe-syntax*
*** Documentation
Describe the syntax specifications in the syntax table of BUFFER.
The descriptions are inserted in a help buffer, which is then displayed.
BUFFER defaults to the current buffer.

(fn &optional BUFFER)
** SPC h t
:PROPERTIES:
:CUSTOM_ID: 914642f8-4c80-49ab-8573-57b29753483d
:END:
*** Function
*help-with-tutorial*
*** Documentation
Select the Emacs learn-by-doing tutorial.
If there is a tutorial version written in the language
of the selected language environment, that version is used.
If there’s no tutorial in that language, ‘TUTORIAL’ is selected.
With ARG, you are asked to choose which language.
If DONT-ASK-FOR-REVERT is non-nil the buffer is reverted without
any question when restarting the tutorial.

If any of the standard Emacs key bindings that are used in the
tutorial have been changed then an explanatory note about this is
shown in the beginning of the tutorial buffer.

When the tutorial buffer is killed the content and the point
position in the buffer is saved so that the tutorial may be
resumed later.

(fn &optional ARG DONT-ASK-FOR-REVERT)
** SPC h v
:PROPERTIES:
:CUSTOM_ID: 0d568527-aeee-4be1-8f2e-af0546a767ce
:END:
*** Function
*describe-variable*
*** Documentation
Display the full documentation of VARIABLE (a symbol).
Returns the documentation as a string, also.
If VARIABLE has a buffer-local value in BUFFER or FRAME
(default to the current buffer and current frame),
it is displayed along with the global value.

(fn VARIABLE &optional BUFFER FRAME)
** SPC h w
:PROPERTIES:
:CUSTOM_ID: 008720ad-b460-43af-979f-de54809b32e9
:END:
*** Function
*where-is*
*** Documentation
Print message listing key sequences that invoke the command DEFINITION.
Argument is a command definition, usually a symbol with a function definition.
If INSERT (the prefix arg) is non-nil, insert the message in the buffer.

(fn DEFINITION &optional INSERT)
** SPC h <f1>
:PROPERTIES:
:CUSTOM_ID: 2477f569-77c8-487d-b97c-4c78e618095f
:END:
*** Function
*help-for-help*
*** Documentation
Help command.
** SPC h <help>
:PROPERTIES:
:CUSTOM_ID: 590fed02-1350-4d6e-b3d6-f2672df8e23b
:END:
*** Function
*help-for-help*
*** Documentation
Help command.
** SPC w C-b
:PROPERTIES:
:CUSTOM_ID: 5af6b7fa-695d-4f38-992d-38e0428063f2
:END:
*** Function
*evil-window-bottom-right*
*** Documentation
Move the cursor to bottom-right window.
** SPC w C-c
:PROPERTIES:
:CUSTOM_ID: 9846b162-0b1d-4ba1-a766-892e9e16f0a2
:END:
*** Function
*ace-delete-window*
*** Documentation
Ace delete window.
** SPC w C-f
:PROPERTIES:
:CUSTOM_ID: b4281713-c994-4f35-8d31-9fdebb2321cb
:END:
*** Function
*ffap-other-window*
*** Documentation
Like ‘ffap’, but put buffer in another window.
Only intended for interactive use.
** SPC w C-h
:PROPERTIES:
:CUSTOM_ID: 5bddd09b-cbc1-4286-bc39-520eadb9ee34
:END:
*** Function
*evil-window-left*
*** Documentation
Move the cursor to new COUNT-th window left of the current one.
** SPC w C-j
:PROPERTIES:
:CUSTOM_ID: 23d27428-7864-49b4-be79-9aa8de38a6ea
:END:
*** Function
*evil-window-down*
*** Documentation
Move the cursor to new COUNT-th window below the current one.
** SPC w C-k
:PROPERTIES:
:CUSTOM_ID: 91a3a7dd-dbbc-4aad-9bfc-99990d23a23e
:END:
*** Function
*evil-window-up*
*** Documentation
Move the cursor to new COUNT-th window above the current one.
** SPC w C-l
:PROPERTIES:
:CUSTOM_ID: fde5e873-8b63-4dc2-a1c4-741cd4896f2f
:END:
*** Function
*evil-window-right*
*** Documentation
Move the cursor to new COUNT-th window right of the current one.
** SPC w C-n
:PROPERTIES:
:CUSTOM_ID: 4b75e306-cdbf-492f-8270-e6c78be29527
:END:
*** Function
*evil-window-new*
*** Documentation
Splits the current window horizontally
and opens a new buffer or edits a certain FILE.
** SPC w C-o
:PROPERTIES:
:CUSTOM_ID: 45307f29-ec24-461e-8637-a38ca19e2bbc
:END:
*** Function
*delete-other-windows*
*** Documentation
Make WINDOW fill its frame.
WINDOW must be a valid window and defaults to the selected one.
Return nil.

If the variable ‘ignore-window-parameters’ is non-nil or the
‘delete-other-windows’ parameter of WINDOW equals t, do not pay
attention to any other parameters of WINDOW.  Otherwise, if the
‘delete-other-windows’ parameter of WINDOW specifies a function,
call that function with WINDOW as its sole argument and return
the value returned by that function.

Else, if WINDOW is part of an atomic window, call this function
with the root of the atomic window as its argument.  Signal an
error if that root window is the root window of WINDOW’s frame.
Also signal an error if WINDOW is a side window.  Do not delete
any window whose ‘no-delete-other-windows’ parameter is non-nil.

(fn &optional WINDOW)
** SPC w C-p
:PROPERTIES:
:CUSTOM_ID: e64d75a3-1342-4fa9-8789-a683ae3452ce
:END:
*** Function
*evil-window-mru*
*** Documentation
Move the cursor to the previous (last accessed) buffer in another window.
More precisely, it selects the most recently used buffer that is
shown in some other window, preferably of the current frame, and
is different from the current one.
** SPC w C-r
:PROPERTIES:
:CUSTOM_ID: c0a158ff-345a-452c-965a-e2eb728aa2a4
:END:
*** Function
*winner-redo*
*** Documentation
Restore a more recent window configuration saved by Winner mode.
** SPC w C-s
:PROPERTIES:
:CUSTOM_ID: 9a602505-f297-41ca-9db2-c4b43902af67
:END:
*** Function
*evil-window-split*
*** Documentation
:override advice: ‘+evil*window-split’

Splits the current window horizontally, COUNT lines height,
editing a certain FILE. The new window will be created below
when ‘evil-split-window-below’ is non-nil. If COUNT and
‘evil-auto-balance-windows’ are both non-nil then all children
of the parent of the splitted window are rebalanced.

(fn &optional COUNT FILE)
** SPC w C-t
:PROPERTIES:
:CUSTOM_ID: 0ac38de5-362f-44c9-bab0-2fc353f3a1d1
:END:
*** Function
*evil-window-top-left*
*** Documentation
Move the cursor to top-left window.
** SPC w C-u
:PROPERTIES:
:CUSTOM_ID: bdda68e8-251c-4cc2-a6fd-2d18b11cfadc
:END:
*** Function
*winner-undo*
*** Documentation
Switch back to an earlier window configuration saved by Winner mode.
In other words, "undo" changes in window configuration.
** SPC w C-v
:PROPERTIES:
:CUSTOM_ID: b87a0553-ef86-4ae0-9b32-7a4049350672
:END:
*** Function
*evil-window-vsplit*
*** Documentation
:override advice: ‘+evil*window-vsplit’

Splits the current window vertically, COUNT columns width,
editing a certain FILE. The new window will be created to the
right when ‘evil-vsplit-window-right’ is non-nil. If COUNT and
‘evil-auto-balance-windows’are both non-nil then all children
of the parent of the splitted window are rebalanced.

(fn &optional COUNT FILE)
** SPC w C-w
:PROPERTIES:
:CUSTOM_ID: 4b1e0a50-27aa-48f0-97b6-0db3f8f49d84
:END:
*** Function
*other-window*
*** Documentation
Select another window in cyclic ordering of windows.
COUNT specifies the number of windows to skip, starting with the
selected window, before making the selection.  If COUNT is
positive, skip COUNT windows forwards.  If COUNT is negative,
skip -COUNT windows backwards.  COUNT zero means do not skip any
window, so select the selected window.  In an interactive call,
COUNT is the numeric prefix argument.  Return nil.

If the ‘other-window’ parameter of the selected window is a
function and ‘ignore-window-parameters’ is nil, call that
function with the arguments COUNT and ALL-FRAMES.

This function does not select a window whose ‘no-other-window’
window parameter is non-nil.

This function uses ‘next-window’ for finding the window to
select.  The argument ALL-FRAMES has the same meaning as in
‘next-window’, but the MINIBUF argument of ‘next-window’ is
always effectively nil.

(fn COUNT &optional ALL-FRAMES)
** SPC w C-_
:PROPERTIES:
:CUSTOM_ID: df103e24-1b91-4a2a-a4f7-1501608fdd40
:END:
*** Function
*evil-window-set-height*
*** Documentation
Sets the height of the current window to COUNT.
** SPC w +
:PROPERTIES:
:CUSTOM_ID: 2346830e-36ce-4a00-87fc-cc0168f50473
:END:
*** Function
*evil-window-increase-height*
*** Documentation
Increase current window height by COUNT.
** SPC w -
:PROPERTIES:
:CUSTOM_ID: 4fafdd2d-8e63-4b7d-b9e2-435cf23e0498
:END:
*** Function
*evil-window-decrease-height*
*** Documentation
Decrease current window height by COUNT.
** SPC w <
:PROPERTIES:
:CUSTOM_ID: c22a7020-bbc2-4f85-8efc-5f3fede855c4
:END:
*** Function
*evil-window-decrease-width*
*** Documentation
Decrease current window width by COUNT.
** SPC w =
:PROPERTIES:
:CUSTOM_ID: 8da312f5-88c3-46ea-9277-fd0bae076ccf
:END:
*** Function
*balance-windows*
*** Documentation
:around advice: ‘+popup*save’

Balance the sizes of windows of WINDOW-OR-FRAME.
WINDOW-OR-FRAME is optional and defaults to the selected frame.
If WINDOW-OR-FRAME denotes a frame, balance the sizes of all
windows of that frame.  If WINDOW-OR-FRAME denotes a window,
recursively balance the sizes of all child windows of that
window.

(fn &optional WINDOW-OR-FRAME)
** SPC w >
:PROPERTIES:
:CUSTOM_ID: 55c87fe1-ebdb-4d7d-83f8-d88870683110
:END:
*** Function
*evil-window-increase-width*
*** Documentation
Increase current window width by COUNT.
** SPC w H
:PROPERTIES:
:CUSTOM_ID: c9da10ce-88c6-4544-8ec1-916c2b82b654
:END:
*** Function
*+evil/window-move-left*
*** Documentation
See ‘+evil--window-swap’

(fn)
** SPC w J
:PROPERTIES:
:CUSTOM_ID: a3440c3e-9040-47c7-a1b1-a1d3e050715f
:END:
*** Function
*+evil/window-move-down*
*** Documentation
See ‘+evil--window-swap’

(fn)
** SPC w K
:PROPERTIES:
:CUSTOM_ID: 01d260c9-baed-4271-9d70-b5375d1e36b5
:END:
*** Function
*+evil/window-move-up*
*** Documentation
See ‘+evil--window-swap’

(fn)
** SPC w L
:PROPERTIES:
:CUSTOM_ID: ddcb4ab9-ea51-4d63-b468-b96c4cc071af
:END:
*** Function
*+evil/window-move-right*
*** Documentation
See ‘+evil--window-swap’

(fn)
** SPC w O
:PROPERTIES:
:CUSTOM_ID: 42e64077-74c7-4394-a9ea-644d10336b11
:END:
*** Function
*doom/window-zoom*
*** Documentation
Close other windows to focus on this one. Activate again to undo this. If the
window changes before then, the undo expires.

Alternatively, use ‘doom/window-enlargen’.
** SPC w R
:PROPERTIES:
:CUSTOM_ID: 480fadd5-d18a-4558-ae87-ad7cffe9e98f
:END:
*** Function
*evil-window-rotate-upwards*
*** Documentation
Rotates the windows according to the currenty cyclic ordering.
** SPC w S
:PROPERTIES:
:CUSTOM_ID: f212ee90-3ec2-4b26-87ca-73ee05d5962a
:END:
*** Function
*evil-window-split*
*** Documentation
:override advice: ‘+evil*window-split’

Splits the current window horizontally, COUNT lines height,
editing a certain FILE. The new window will be created below
when ‘evil-split-window-below’ is non-nil. If COUNT and
‘evil-auto-balance-windows’ are both non-nil then all children
of the parent of the splitted window are rebalanced.

(fn &optional COUNT FILE)
** SPC w W
:PROPERTIES:
:CUSTOM_ID: 9d2962d2-055d-4031-9258-3d24f3c28154
:END:
*** Function
*evil-window-prev*
*** Documentation
Move the cursor to the previous window in the cyclic order.
With COUNT go to the count-th window in the order starting from
top-left.
** SPC w _
:PROPERTIES:
:CUSTOM_ID: 3b93c8cf-1d66-4c47-9309-6482f34d884f
:END:
*** Function
*evil-window-set-height*
*** Documentation
Sets the height of the current window to COUNT.
** SPC w b
:PROPERTIES:
:CUSTOM_ID: b3d4402a-1b58-4f12-884e-726a4f34e8d7
:END:
*** Function
*evil-window-bottom-right*
*** Documentation
Move the cursor to bottom-right window.
** SPC w c
:PROPERTIES:
:CUSTOM_ID: 537bc383-a1b3-4bc9-b370-c171846c1e8e
:END:
*** Function
*+workspace/close-window-or-workspace*
*** Documentation
Close the selected window. If it’s the last window in the workspace, either
close the workspace (as well as its associated frame, if one exists) and move to
the next.
** SPC w h
:PROPERTIES:
:CUSTOM_ID: 9f8d7465-2730-46bc-aecc-e66ce3f54ba6
:END:
*** Function
*evil-window-left*
*** Documentation
Move the cursor to new COUNT-th window left of the current one.
** SPC w j
:PROPERTIES:
:CUSTOM_ID: 8942711b-463d-44f0-ae1d-25e6e3c4b552
:END:
*** Function
*evil-window-down*
*** Documentation
Move the cursor to new COUNT-th window below the current one.
** SPC w k
:PROPERTIES:
:CUSTOM_ID: 36d4d244-9c84-4a03-b77a-c5573183be5b
:END:
*** Function
*evil-window-up*
*** Documentation
Move the cursor to new COUNT-th window above the current one.
** SPC w l
:PROPERTIES:
:CUSTOM_ID: 87ea4869-4cca-4d1e-b776-68cbafebf11d
:END:
*** Function
*evil-window-right*
*** Documentation
Move the cursor to new COUNT-th window right of the current one.
** SPC w n
:PROPERTIES:
:CUSTOM_ID: 798368f5-b3b5-40f2-8532-428e83cc328b
:END:
*** Function
*evil-window-new*
*** Documentation
Splits the current window horizontally
and opens a new buffer or edits a certain FILE.
** SPC w o
:PROPERTIES:
:CUSTOM_ID: c3ee1228-7bd5-4caf-b9fb-536b557aeeae
:END:
*** Function
*doom/window-enlargen*
*** Documentation
Enlargen the current window to focus on this one. Does not close other
windows (unlike ‘doom/window-zoom’) Activate again to undo.
** SPC w p
:PROPERTIES:
:CUSTOM_ID: ad87cc70-aace-435e-891d-bf1741aec654
:END:
*** Function
*evil-window-mru*
*** Documentation
Move the cursor to the previous (last accessed) buffer in another window.
More precisely, it selects the most recently used buffer that is
shown in some other window, preferably of the current frame, and
is different from the current one.
** SPC w q
:PROPERTIES:
:CUSTOM_ID: fe3377ad-1cc2-4369-88aa-81cfc01adfe7
:END:
*** Function
*evil-quit*
*** Documentation
Closes the current window, current frame, Emacs.
If the current frame belongs to some client the client connection
is closed.
** SPC w r
:PROPERTIES:
:CUSTOM_ID: 46e648bd-ba31-4706-81ad-45f76e385e98
:END:
*** Function
*evil-window-rotate-downwards*
*** Documentation
Rotates the windows according to the currenty cyclic ordering.
** SPC w s
:PROPERTIES:
:CUSTOM_ID: 77f8324e-8b68-49b5-af98-ffca2d83f80c
:END:
*** Function
*evil-window-split*
*** Documentation
:override advice: ‘+evil*window-split’

Splits the current window horizontally, COUNT lines height,
editing a certain FILE. The new window will be created below
when ‘evil-split-window-below’ is non-nil. If COUNT and
‘evil-auto-balance-windows’ are both non-nil then all children
of the parent of the splitted window are rebalanced.

(fn &optional COUNT FILE)
** SPC w t
:PROPERTIES:
:CUSTOM_ID: 1642cbef-e2b0-44e1-a4f5-d908b5768698
:END:
*** Function
*evil-window-top-left*
*** Documentation
Move the cursor to top-left window.
** SPC w u
:PROPERTIES:
:CUSTOM_ID: be04a0ed-bed5-4198-9eb9-a2b4986ea012
:END:
*** Function
*winner-undo*
*** Documentation
Switch back to an earlier window configuration saved by Winner mode.
In other words, "undo" changes in window configuration.
** SPC w v
:PROPERTIES:
:CUSTOM_ID: fe3b666d-1baa-4e7e-a578-503c303b16d9
:END:
*** Function
*evil-window-vsplit*
*** Documentation
:override advice: ‘+evil*window-vsplit’

Splits the current window vertically, COUNT columns width,
editing a certain FILE. The new window will be created to the
right when ‘evil-vsplit-window-right’ is non-nil. If COUNT and
‘evil-auto-balance-windows’are both non-nil then all children
of the parent of the splitted window are rebalanced.

(fn &optional COUNT FILE)
** SPC w w
:PROPERTIES:
:CUSTOM_ID: eee43689-5cfe-4e1c-b701-6135193b35f5
:END:
*** Function
*evil-window-next*
*** Documentation
Move the cursor to the next window in the cyclic order.
With COUNT go to the count-th window in the order starting from
top-left.
** SPC w |
:PROPERTIES:
:CUSTOM_ID: 10cf43ab-675d-4722-8ce3-3486a50885a3
:END:
*** Function
*evil-window-set-width*
*** Documentation
Sets the width of the current window to COUNT.
** SPC w C-S-h
:PROPERTIES:
:CUSTOM_ID: f2ad9ebd-e051-4c64-bafa-bd09e069c8f1
:END:
*** Function
*evil-window-move-far-left*
*** Documentation
:around advice: ‘+popup*save’

Closes the current window, splits the upper-left one vertically
and redisplays the current buffer there.

(fn)
** SPC w C-S-j
:PROPERTIES:
:CUSTOM_ID: 3694f5a2-9d09-4163-bf69-0450db285c6b
:END:
*** Function
*evil-window-move-very-bottom*
*** Documentation
:around advice: ‘+popup*save’

Closes the current window, splits the lower-right one horizontally
and redisplays the current buffer there.

(fn)
** SPC w C-S-k
:PROPERTIES:
:CUSTOM_ID: 4d514dd3-2cc6-46c7-a71b-8c34822f75f5
:END:
*** Function
*evil-window-move-very-top*
*** Documentation
:around advice: ‘+popup*save’

Closes the current window, splits the upper-left one horizontally
and redisplays the current buffer there.

(fn)
** SPC w C-S-l
:PROPERTIES:
:CUSTOM_ID: addaa83b-5a3b-4ab2-a3ac-066212bfab22
:END:
*** Function
*evil-window-move-far-right*
*** Documentation
:around advice: ‘+popup*save’

Closes the current window, splits the lower-right one vertically
and redisplays the current buffer there.

(fn)
** SPC w C-S-r
:PROPERTIES:
:CUSTOM_ID: d6e54d0b-287a-4190-b46b-bd3b989cee1b
:END:
*** Function
*evil-window-rotate-upwards*
*** Documentation
Rotates the windows according to the currenty cyclic ordering.
** SPC w C-S-s
:PROPERTIES:
:CUSTOM_ID: dda0bf3d-25cc-4983-a60d-9fcc312c77c0
:END:
*** Function
*evil-window-split*
*** Documentation
:override advice: ‘+evil*window-split’

Splits the current window horizontally, COUNT lines height,
editing a certain FILE. The new window will be created below
when ‘evil-split-window-below’ is non-nil. If COUNT and
‘evil-auto-balance-windows’ are both non-nil then all children
of the parent of the splitted window are rebalanced.

(fn &optional COUNT FILE)
** SPC w C-S-w
:PROPERTIES:
:CUSTOM_ID: 9d756624-ff89-4e42-8b3e-d59209a4f1dc
:END:
*** Function
*ace-swap-window*
*** Documentation
Ace swap window.
** SPC o a a
:PROPERTIES:
:CUSTOM_ID: d0864d70-7e7a-47ad-ae7a-40bf6e38a8bc
:END:
*** Function
*org-agenda*
*** Documentation
Dispatch agenda commands to collect entries to the agenda buffer.
Prompts for a command to execute.  Any prefix arg will be passed
on to the selected command.  The default selections are:

a     Call ‘org-agenda-list’ to display the agenda for current day or week.
t     Call ‘org-todo-list’ to display the global todo list.
T     Call ‘org-todo-list’ to display the global todo list, select only
      entries with a specific TODO keyword (the user gets a prompt).
m     Call ‘org-tags-view’ to display headlines with tags matching
      a condition  (the user is prompted for the condition).
M     Like ‘m’, but select only TODO entries, no ordinary headlines.
e     Export views to associated files.
s     Search entries for keywords.
S     Search entries for keywords, only with TODO keywords.
/     Multi occur across all agenda files and also files listed
      in ‘org-agenda-text-search-extra-files’.
<     Restrict agenda commands to buffer, subtree, or region.
      Press several times to get the desired effect.
>     Remove a previous restriction.
#     List "stuck" projects.
!     Configure what "stuck" means.
C     Configure custom agenda commands.

More commands can be added by configuring the variable
‘org-agenda-custom-commands’.  In particular, specific tags and TODO keyword
searches can be pre-defined in this way.

If the current buffer is in Org mode and visiting a file, you can also
first press ‘<’ once to indicate that the agenda should be temporarily
(until the next use of ‘SPC o A’) restricted to the current file.
Pressing ‘<’ twice means to restrict to the current subtree or region
(if active).
** SPC o a m
:PROPERTIES:
:CUSTOM_ID: 8f20b935-6658-4287-ae92-95380361a784
:END:
*** Function
*org-tags-view*
*** Documentation
Show all headlines for all ‘org-agenda-files’ matching a TAGS criterion.
The prefix arg TODO-ONLY limits the search to TODO entries.
** SPC o a t
:PROPERTIES:
:CUSTOM_ID: 57555522-56af-4599-b847-b3cf2083a60f
:END:
*** Function
*org-todo-list*
*** Documentation
Show all (not done) TODO entries from all agenda file in a single list.
The prefix arg can be used to select a specific TODO keyword and limit
the list to these.  When using ‘SPC u’, you will be prompted
for a keyword.  A numeric prefix directly selects the Nth keyword in
‘org-todo-keywords-1’.
** SPC o a v
:PROPERTIES:
:CUSTOM_ID: 31217721-9d95-4426-868a-89e41eb23a57
:END:
*** Function
*org-search-view*
*** Documentation
Show all entries that contain a phrase or words or regular expressions.

With optional prefix argument TODO-ONLY, only consider entries that are
TODO entries.  The argument STRING can be used to pass a default search
string into this function.  If EDIT-AT is non-nil, it means that the
user should get a chance to edit this string, with cursor at position
EDIT-AT.

The search string can be viewed either as a phrase that should be found as
is, or it can be broken into a number of snippets, each of which must match
in a Boolean way to select an entry.  The default depends on the variable
‘org-agenda-search-view-always-boolean’.
Even if this is turned off (the default) you can always switch to
Boolean search dynamically by preceding the first word with  "+" or "-".

The default is a direct search of the whole phrase, where each space in
the search string can expand to an arbitrary amount of whitespace,
including newlines.

If using a Boolean search, the search string is split on whitespace and
each snippet is searched separately, with logical AND to select an entry.
Words prefixed with a minus must *not* occur in the entry.  Words without
a prefix or prefixed with a plus must occur in the entry.  Matching is
case-insensitive.  Words are enclosed by word delimiters (i.e. they must
match whole words, not parts of a word) if
‘org-agenda-search-view-force-full-words’ is set (default is nil).

Boolean search snippets enclosed by curly braces are interpreted as
regular expressions that must or (when preceded with "-") must not
match in the entry.  Snippets enclosed into double quotes will be taken
as a whole, to include whitespace.

- If the search string starts with an asterisk, search only in headlines.
- If (possibly after the leading star) the search string starts with an
  exclamation mark, this also means to look at TODO entries only, an effect
  that can also be achieved with a prefix argument.
- If (possibly after star and exclamation mark) the search string starts
  with a colon, this will mean that the (non-regexp) snippets of the
  Boolean search must match as full words.

This command searches the agenda files, and in addition the files
listed in ‘org-agenda-text-search-extra-files’ unless a restriction lock
is active.
** SPC g c R
:PROPERTIES:
:CUSTOM_ID: f4be7cde-5467-4e39-8c00-35dbd343b790
:END:
*** Function
*+magit/clone*
*** Documentation
Like ‘magit-clone’, but supports additional formats on top of absolute URLs:

+ USER/REPO: assumes {‘+magit-default-clone-url’}/USER/REPO
+ REPO: assumes {‘+magit-default-clone-url’}/{USER}/REPO, where {USER} is
  ascertained from your global gitconfig.
** SPC g c c
:PROPERTIES:
:CUSTOM_ID: cd606ac1-b327-48b0-bafe-8012d1227fec
:END:
*** Function
*magit-commit-create*
*** Documentation
Create a new commit on ‘HEAD’.
With a prefix argument, amend to the commit at ‘HEAD’ instead.

(git commit [--amend] ARGS)

(fn &optional ARGS)
** SPC g c i
:PROPERTIES:
:CUSTOM_ID: 7328b26c-a017-4b3a-9ba7-f5abb2ac8912
:END:
*** Function
*forge-create-issue*
*** Documentation
Create a new issue for the current repository.
** SPC g c p
:PROPERTIES:
:CUSTOM_ID: 8174ba6d-e053-43f4-b59e-db7a536b9ef0
:END:
*** Function
*forge-create-pullreq*
*** Documentation
Create a new pull-request for the current repository.

(fn SOURCE TARGET)
** SPC g c r
:PROPERTIES:
:CUSTOM_ID: 14b3e79b-af58-4a94-b85a-a42d89b17109
:END:
*** Function
*magit-init*
*** Documentation
Initialize a Git repository, then show its status.

If the directory is below an existing repository, then the user
has to confirm that a new one should be created inside.  If the
directory is the root of the existing repository, then the user
has to confirm that it should be reinitialized.

Non-interactively DIRECTORY is (re-)initialized unconditionally.

(fn DIRECTORY)
** SPC g l i
:PROPERTIES:
:CUSTOM_ID: 57108eb1-8c65-4514-8211-197ce2073ce4
:END:
*** Function
*forge-list-issues*
*** Documentation
List issues in a separate buffer.

(fn REPO)
** SPC g l n
:PROPERTIES:
:CUSTOM_ID: 225709e5-83cf-4fe7-abab-c73cabb553e6
:END:
*** Function
*forge-list-notifications*
*** Documentation
List notifications.
** SPC g l p
:PROPERTIES:
:CUSTOM_ID: 6d9dec9e-4db2-4a8d-8ef1-2186c2ec5a04
:END:
*** Function
*forge-list-pullreqs*
*** Documentation
List pull-requests in a separate buffer.

(fn REPO)
** SPC g l r
:PROPERTIES:
:CUSTOM_ID: c7759972-c993-43fd-b6b7-4838d893a77c
:END:
*** Function
*magit-list-repositories*
*** Documentation
Display a list of repositories.

Use the options ‘magit-repository-directories’ to control which
repositories are displayed.
** SPC g l s
:PROPERTIES:
:CUSTOM_ID: cfb7c996-8c12-4be2-a188-fb7090d22bfb
:END:
*** Function
*magit-list-submodules*
*** Documentation
Display a list of the current repository’s submodules.
** SPC g o .
:PROPERTIES:
:CUSTOM_ID: ccd9bb82-35f7-4118-81c2-3c19f31ba507
:END:
*** Function
*+vc/git-browse-region-or-line*
*** Documentation
Open the website for the current version controlled file. Fallback to
repository root.

(fn &optional ARG)
** SPC g o I
:PROPERTIES:
:CUSTOM_ID: 452e1ee3-94c6-4892-baa0-e3cbf083d955
:END:
*** Function
*forge-browse-issues*
*** Documentation
Visit the url corresponding to REPO’s issues using a browser.

(fn REPO)
** SPC g o P
:PROPERTIES:
:CUSTOM_ID: 43243d71-5c54-46c3-b51f-d2f4d2f114fc
:END:
*** Function
*forge-browse-pullreqs*
*** Documentation
Visit the url corresponding to REPO’s pull-requests using a browser.

(fn REPO)
** SPC g o c
:PROPERTIES:
:CUSTOM_ID: e6637c74-9087-4cbb-8279-a665ec21b62e
:END:
*** Function
*forge-browse-commit*
*** Documentation
Visit the url corresponding to REV using a browser.

(fn REV)
** SPC g o i
:PROPERTIES:
:CUSTOM_ID: 6aa421fa-afbc-4b9b-b097-496d49c1109e
:END:
*** Function
*forge-browse-issue*
*** Documentation
Visit the url corresponding to ISSUE using a browser.

(fn ISSUE)
** SPC g o p
:PROPERTIES:
:CUSTOM_ID: 5dcfbdcb-3156-4226-925d-437b0eddb41b
:END:
*** Function
*forge-browse-pullreq*
*** Documentation
Visit the url corresponding to PULLREQ using a browser.

(fn PULLREQ)
** SPC g o r
:PROPERTIES:
:CUSTOM_ID: 182c0b40-a9e2-4236-a89a-3ac64bb48fc3
:END:
*** Function
*forge-browse-remote*
*** Documentation
Visit the url corresponding to REMOTE using a browser.

(fn REMOTE)
** SPC g f c
:PROPERTIES:
:CUSTOM_ID: 6b7a629d-6bf6-4a76-965d-4066280988c5
:END:
*** Function
*magit-show-commit*
*** Documentation
Visit the revision at point in another buffer.
If there is no revision at point or with a prefix argument prompt
for a revision.

(fn REV &optional ARGS FILES MODULE)
** SPC g f f
:PROPERTIES:
:CUSTOM_ID: 86f5d314-2e50-4f2e-8500-c78b780fc00e
:END:
*** Function
*magit-find-file*
*** Documentation
View FILE from REV.
Switch to a buffer visiting blob REV:FILE,
creating one if none already exists.

(fn REV FILE)
** SPC g f g
:PROPERTIES:
:CUSTOM_ID: 077c5d67-8fa3-48fc-a08b-744b8c2beb0e
:END:
*** Function
*magit-find-git-config-file*
*** Documentation
Edit a file located in the current repository’s git directory.

When ".git", located at the root of the working tree, is a
regular file, then that makes it cumbersome to open a file
located in the actual git directory.

This command is like ‘find-file’, except that it temporarily
binds ‘default-directory’ to the actual git directory, while
reading the FILENAME.

(fn FILENAME &optional WILDCARDS)
** SPC g f i
:PROPERTIES:
:CUSTOM_ID: 5958338c-bf28-46bc-b0c0-b137fc9d5082
:END:
*** Function
*forge-visit-issue*
*** Documentation
View the issue at point in a separate buffer.

(fn ISSUE)
** SPC g f p
:PROPERTIES:
:CUSTOM_ID: d32a6b0c-f2f5-468b-b26d-88a717f753c9
:END:
*** Function
*forge-visit-pullreq*
*** Documentation
View the pull-request at point in a separate buffer.

(fn PULLREQ)
** SPC h r P
:PROPERTIES:
:CUSTOM_ID: 2201b894-1e0e-4dd4-987e-4e65685d6749
:END:
*** Function
*doom/reload-project*
*** Documentation
Reload the project root cache.
** SPC h r f
:PROPERTIES:
:CUSTOM_ID: 21d92b57-2205-4dbb-886a-f3336695a92b
:END:
*** Function
*doom/reload-font*
*** Documentation
Reload ‘doom-font’, ‘doom-variable-pitch-font’, and ‘doom-unicode-font’, if
set.
** SPC h r p
:PROPERTIES:
:CUSTOM_ID: 94759093-d634-4121-8011-53a323c3d8e6
:END:
*** Function
*doom/reload-packages*
*** Documentation
Reload ‘doom-packages’, ‘package’ and ‘quelpa’.
** SPC h r r
:PROPERTIES:
:CUSTOM_ID: eccc3764-d1ea-4c9f-8948-a5e69b287d66
:END:
*** Function
*doom/reload*
*** Documentation
Reloads your config. This is experimental!

If called from a noninteractive session, this will try to communicate with a
live server (if one is found) to tell it to run this function.

If called from an interactive session, tries to reload autoloads files (if
necessary), reinistalize doom (via ‘doom-initialize’) and reloads your private
init.el and config.el. Then runs ‘doom-reload-hook’.

(fn &optional FORCE-P)
** SPC h r t
:PROPERTIES:
:CUSTOM_ID: 3bf5d7ff-8496-4e36-985f-a36310f6d6f2
:END:
*** Function
*doom/reload-theme*
*** Documentation
Reset the current color theme and fonts.
** SPC h 4 i
:PROPERTIES:
:CUSTOM_ID: c128a286-6e89-4174-8b91-048dc1c9cb73
:END:
*** Function
*info-other-window*
*** Documentation
Like ‘info’ but show the Info buffer in another window.

(fn &optional FILE-OR-NODE BUFFER)
** SPC m T
:PROPERTIES:
:CUSTOM_ID: 7db925a0-16fd-4a34-9dc8-31db11e253fe
:END:
*** Function
*org-todo-list*
*** Documentation
Show all (not done) TODO entries from all agenda file in a single list.
The prefix arg can be used to select a specific TODO keyword and limit
the list to these.  When using ‘SPC u’, you will be prompted
for a keyword.  A numeric prefix directly selects the Nth keyword in
‘org-todo-keywords-1’.
** SPC m b
:PROPERTIES:
:CUSTOM_ID: cca6a822-c3c5-4ec6-9595-3eb1cf9208eb
:END:
*** Function
*org-switchb*
*** Documentation
Switch between Org buffers.

With ‘SPC u’ prefix, restrict available buffers to files.

With ‘SPC u SPC u’ prefix, restrict available buffers to agenda files.

(fn &optional ARG)
** SPC m d
:PROPERTIES:
:CUSTOM_ID: 1045bdf1-ac13-43ad-a5f5-b067b440cfb8
:END:
*** Function
*org-deadline*
*** Documentation
Insert the "DEADLINE:" string with a timestamp to make a deadline.
With one universal prefix argument, remove any deadline from the item.
With two universal prefix arguments, prompt for a warning delay.
With argument TIME, set the deadline at the corresponding date.  TIME
can either be an Org date like "2011-07-24" or a delta like "+2d".

(fn ARG &optional TIME)
** SPC m l
:PROPERTIES:
:CUSTOM_ID: 5be3b6e9-d8a5-4b9a-80f0-6a2103a8ed84
:END:
*** Function
*org-store-link*
*** Documentation
Store a link to the current location.

This link is added to ‘org-stored-links’ and can later be inserted
into an Org buffer with ‘org-insert-link’ (‘C-c C-l’).

For some link types, a ‘M-x universal-argument’ prefix ARG is interpreted.  A single
‘M-x universal-argument’ negates ‘org-context-in-file-links’ for file links or
‘org-gnus-prefer-web-links’ for links to Usenet articles.

A ‘M-x universal-argument M-x universal-argument’ prefix ARG forces skipping storing functions that are not
part of Org core.

A ‘M-x universal-argument M-x universal-argument M-x universal-argument’ prefix ARG forces storing a link for each line in the
active region.

Assume the function is called interactively if INTERACTIVE? is
non-nil.

(fn ARG &optional INTERACTIVE\?)
** SPC m t
:PROPERTIES:
:CUSTOM_ID: 8aa0c3b4-fbf6-43e5-892e-fc119f243145
:END:
*** Function
*org-todo*
*** Documentation
Change the TODO state of an item.

The state of an item is given by a keyword at the start of the heading,
like
     *** TODO Write paper
     *** DONE Call mom

The different keywords are specified in the variable ‘org-todo-keywords’.
By default the available states are "TODO" and "DONE".  So, for this
example: when the item starts with TODO, it is changed to DONE.
When it starts with DONE, the DONE is removed.  And when neither TODO nor
DONE are present, add TODO at the beginning of the heading.

With ‘SPC u’ prefix ARG, use completion to determine the new state.
With numeric prefix ARG, switch to that state.
With a ‘SPC u SPC u’ prefix, switch to the next set of TODO keywords (nextset).
With a ‘SPC u SPC u SPC u’ prefix, circumvent any state blocking.
With a numeric prefix arg of 0, inhibit note taking for the change.
With a numeric prefix arg of -1, cancel repeater to allow marking as DONE.

When called through ELisp, arg is also interpreted in the following way:
‘none’        -> empty state
""            -> switch to empty state
‘done’        -> switch to DONE
‘nextset’     -> switch to the next set of keywords
‘previousset’ -> switch to the previous set of keywords
"WAITING"     -> switch to the specified keyword, but only if it
                 really is a member of ‘org-todo-keywords’.

(fn &optional ARG)
** SPC m e M
:PROPERTIES:
:CUSTOM_ID: 8cc8ffb0-da2a-41ff-831b-5f07bbb91f8a
:END:
*** Function
*org-md-export-as-markdown*
*** Documentation
Export current buffer to a Markdown buffer.

If narrowing is active in the current buffer, only export its
narrowed part.

If a region is active, export that region.

A non-nil optional argument ASYNC means the process should happen
asynchronously.  The resulting buffer should be accessible
through the ‘org-export-stack’ interface.

When optional argument SUBTREEP is non-nil, export the sub-tree
at point, extracting information from the headline properties
first.

When optional argument VISIBLE-ONLY is non-nil, don’t export
contents of hidden elements.

Export is done in a buffer named "*Org MD Export*", which will
be displayed when ‘org-export-show-temporary-export-buffer’ is
non-nil.

(fn &optional ASYNC SUBTREEP VISIBLE-ONLY)
** SPC m e R
:PROPERTIES:
:CUSTOM_ID: 29a2cc23-01b8-4421-9bbb-4bc7de5f2893
:END:
*** Function
*org-reveal-export-to-html-and-browse*
*** Documentation
Export current buffer to a reveal.js and browse HTML file.
** SPC m e m
:PROPERTIES:
:CUSTOM_ID: 3c5332fa-b591-4632-99c6-a23c5610f214
:END:
*** Function
*org-md-export-to-markdown*
*** Documentation
Export current buffer to a Markdown file.

If narrowing is active in the current buffer, only export its
narrowed part.

If a region is active, export that region.

A non-nil optional argument ASYNC means the process should happen
asynchronously.  The resulting file should be accessible through
the ‘org-export-stack’ interface.

When optional argument SUBTREEP is non-nil, export the sub-tree
at point, extracting information from the headline properties
first.

When optional argument VISIBLE-ONLY is non-nil, don’t export
contents of hidden elements.

Return output file’s name.

(fn &optional ASYNC SUBTREEP VISIBLE-ONLY)
** SPC m e r
:PROPERTIES:
:CUSTOM_ID: de0c9d8a-5112-4598-ad5b-2a418024d98f
:END:
*** Function
*org-reveal-export-to-html*
*** Documentation
Export current buffer to a reveal.js HTML file.
** SPC m c C
:PROPERTIES:
:CUSTOM_ID: 76eda266-e262-44da-b736-d3c0fc02c453
:END:
*** Function
*org-clock-out*
*** Documentation
Stop the currently running clock.
Throw an error if there is no running clock and FAIL-QUIETLY is nil.
With a universal prefix, prompt for a state to switch the clocked out task
to, overriding the existing value of ‘org-clock-out-switch-to-state’.

(fn &optional SWITCH-TO-STATE FAIL-QUIETLY AT-TIME)
** SPC m c c
:PROPERTIES:
:CUSTOM_ID: c2b90f65-f0c4-4f62-9049-a567a28b66db
:END:
*** Function
*org-clock-in*
*** Documentation
Start the clock on the current item.

If necessary, clock-out of the currently active clock.

With a ‘SPC u’ prefix argument SELECT, offer a list of recently clocked
tasks to clock into.

When SELECT is ‘SPC u SPC u’, clock into the current task and mark it as
the default task, a special task that will always be offered in the
clocking selection, associated with the letter ‘d’.

When SELECT is ‘SPC u SPC u SPC u’, clock in by using the last clock-out
time as the start time.  See ‘org-clock-continuously’ to make this
the default behavior.

(fn &optional SELECT START-TIME)
** SPC m c g
:PROPERTIES:
:CUSTOM_ID: 02bdcf39-e46e-47a3-b7be-afab6bca2b06
:END:
*** Function
*org-clock-goto*
*** Documentation
Go to the currently clocked-in entry, or to the most recently clocked one.
With prefix arg SELECT, offer recently clocked tasks for selection.

(fn &optional SELECT)
** SPC m c x
:PROPERTIES:
:CUSTOM_ID: f0aaaacc-fc23-46b0-8f0a-bcbaf226df82
:END:
*** Function
*org-clock-cancel*
*** Documentation
Cancel the running clock by removing the start timestamp.
** SPC m e b L
:PROPERTIES:
:CUSTOM_ID: e041a4d0-bdcf-4ff8-8081-ce4bed7eb304
:END:
*** Function
*org-beamer-export-as-latex*
*** Documentation
Export current buffer as a Beamer buffer.

If narrowing is active in the current buffer, only export its
narrowed part.

If a region is active, export that region.

A non-nil optional argument ASYNC means the process should happen
asynchronously.  The resulting buffer should be accessible
through the ‘org-export-stack’ interface.

When optional argument SUBTREEP is non-nil, export the sub-tree
at point, extracting information from the headline properties
first.

When optional argument VISIBLE-ONLY is non-nil, don’t export
contents of hidden elements.

When optional argument BODY-ONLY is non-nil, only write code
between "\begin{document}" and "\end{document}".

EXT-PLIST, when provided, is a property list with external
parameters overriding Org default settings, but still inferior to
file-local settings.

Export is done in a buffer named "*Org BEAMER Export*", which
will be displayed when ‘org-export-show-temporary-export-buffer’
is non-nil.

(fn &optional ASYNC SUBTREEP VISIBLE-ONLY BODY-ONLY EXT-PLIST)
** SPC m e b l
:PROPERTIES:
:CUSTOM_ID: 9e5b67be-850d-491d-8b45-a9e30d289ed9
:END:
*** Function
*org-beamer-export-to-latex*
*** Documentation
Export current buffer as a Beamer presentation (tex).

If narrowing is active in the current buffer, only export its
narrowed part.

If a region is active, export that region.

A non-nil optional argument ASYNC means the process should happen
asynchronously.  The resulting file should be accessible through
the ‘org-export-stack’ interface.

When optional argument SUBTREEP is non-nil, export the sub-tree
at point, extracting information from the headline properties
first.

When optional argument VISIBLE-ONLY is non-nil, don’t export
contents of hidden elements.

When optional argument BODY-ONLY is non-nil, only write code
between "\begin{document}" and "\end{document}".

EXT-PLIST, when provided, is a property list with external
parameters overriding Org default settings, but still inferior to
file-local settings.

Return output file’s name.

(fn &optional ASYNC SUBTREEP VISIBLE-ONLY BODY-ONLY EXT-PLIST)
** SPC m e b p
:PROPERTIES:
:CUSTOM_ID: e26eee8c-b4e3-40bd-81ea-69910c34fd8d
:END:
*** Function
*org-beamer-export-to-pdf*
*** Documentation
Export current buffer as a Beamer presentation (PDF).

If narrowing is active in the current buffer, only export its
narrowed part.

If a region is active, export that region.

A non-nil optional argument ASYNC means the process should happen
asynchronously.  The resulting file should be accessible through
the ‘org-export-stack’ interface.

When optional argument SUBTREEP is non-nil, export the sub-tree
at point, extracting information from the headline properties
first.

When optional argument VISIBLE-ONLY is non-nil, don’t export
contents of hidden elements.

When optional argument BODY-ONLY is non-nil, only write code
between "\begin{document}" and "\end{document}".

EXT-PLIST, when provided, is a property list with external
parameters overriding Org default settings, but still inferior to
file-local settings.

Return PDF file’s name.

(fn &optional ASYNC SUBTREEP VISIBLE-ONLY BODY-ONLY EXT-PLIST)
